### ISSUE TITLE
responsiveness issue

### ISSUE THREAD

**Issue by SatyaJaiss** [ankit071105/Ticket-Booking#1]
poor responsiveness of the nav bar
![Screenshot 2024-10-01 185341](https://github.com/user-attachments/assets/77ae36b0-2853-4279-8518-db90e20b346b)

it can be easily resolved, kindly assign it to me

**Comment by SatyaJaiss** [comment]
Why it got closed, the issue isn't resolved yet, actually I was working on another project, kindly assign it again to me, I will get it done by 12:00am

**Comment by ankit071105** [comment]
> Why it got closed, the issue isn't resolved yet, actually I was working on another project, kindly assign it again to me, I will get it done by 12:00am

already assigned

**Comment by SatyaJaiss** [comment]
@ankit071105 I've solved the issue, kindly review. I've also made PR.
