### ISSUE TITLE
create a sign up/ login form

### ISSUE THREAD

**Issue by ParulPrashar** [ankit071105/Ticket-Booking#10]
To track customer details and history it is very important to add a new sign up and log in form. Also mentioning it in nav bar

**Comment by ankit071105** [comment]
> To track customer details and history it is very important to add a new sign up and log in form. Also mentioning it in nav bar

If you want to create create it but not only the front end part backend too

**Comment by saurabhvybs** [comment]
You can assign this to me... i can handle both frontend and backend of it and effectively provide you the solution. i love the authentication part just tell me what are the data i need to get from the user i am good to go

**Comment by ankit071105** [comment]
> You can assign this to me... i can handle both frontend and backend of it and effectively provide you the solution. i love the authentication part just tell me what are the data i need to get from the user i am good to go

okay i am assiging it you but make it complete resposnsive

**Comment by saurabhvybs** [comment]
@ankit071105 Can You Tell Me What Are the fields you want to keep in signup Form . Is only Email Username Password is ok ? or you want some additional info to be taken at the time of Registration ?

**Comment by ankit071105** [comment]
Yes in signing the purpose add option to sign with Google and Facebook

**Comment by saurabhvybs** [comment]
will Add the login through google and fb in part 2 for now opened a PR with jwt authentication

**Comment by ankit071105** [comment]
> will Add the login through google and fb in part 2 for now opened a PR with jwt authentication

yes you can

**Comment by SHUBHAG100520** [comment]
Can i work on it
