### ISSUE TITLE
Header Issue In the Index Page

### ISSUE THREAD

**Issue by 31Rishita** [ankit071105/Ticket-Booking#1007]
## Description
In the index page the header is not proper I can make it proper
Please assign me this issue
<img width="960" alt="{F92DF556-935C-44D3-9F9A-D639BEA10D13}" src="https://github.com/user-attachments/assets/43f40c8f-3a2e-4b8e-bce0-79a465dae19f">

**Comment by veepanshu-kasana** [comment]
@ankit071105 I want to contribute to this project on this particular issue. Please assign it to me!
