### ISSUE TITLE
Contribute Page Header Issue

### ISSUE THREAD

**Issue by 31Rishita** [ankit071105/Ticket-Booking#1008]
## Description
The header in the contribute page is not proper
Please assign me this issue

<img width="957" alt="{41161387-A3B6-49C7-8E2B-0C3AA9744B11}" src="https://github.com/user-attachments/assets/de1137c4-0751-4203-94b6-a96458ac9604">

**Comment by veepanshu-kasana** [comment]
@ankit071105 I want to contribute to this project on this particular issue. Please assign it to me!

**Comment by 31Rishita** [comment]
@veepanshu-kasana This issue is already posted by me so can u please post your own new issue other than this.
