### ISSUE TITLE
[BUG] Navbar Correct

### ISSUE THREAD

**Issue by hardikguptaofficialgit** [ankit071105/Ticket-Booking#1030]
### Description

Navbar is not good and all elements of it are unaligned so i will make it better so assgn me the task

### Screenshots

![image](https://github.com/user-attachments/assets/64ce5350-690c-422c-9a59-04c569aace6c)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/ankit071105/Ticket-Booking/blob/main/README.md)
- [X] I'm a GSSoC'24-Extd contributor
- [ ] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by BhavikaPachauri** [comment]
i  want to work on this issue if it is open
