### ISSUE TITLE
[BUG] No Proper Styling for Contibutors and Login Button

### ISSUE THREAD

**Issue by varshasric4** [ankit071105/Ticket-Booking#1043]
### Description

In this page there is no styling for the buttons like contributors and Login button 
only Html tags have been assigned.
This mistake will dissappoint the users and effects the user friendly environment in the webstite page

### Screenshots

[
![IMG_20241107_135216](https://github.com/user-attachments/assets/601cff66-ca1a-4b7a-b584-db770d6dd788)
](url)

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/ankit071105/Ticket-Booking/blob/main/README.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by Rohan1786** [comment]
iam ready to work on this please assign to me
