### ISSUE TITLE
[BUG] There is no proper submit button with css styling 

### ISSUE THREAD

**Issue by varshasric4** [ankit071105/Ticket-Booking#1045]
### Description

In the sell page in the tickets website .There is no proper button to submit 
it is just white circle which is not exactly like a button .
The text is also not visible on the button it is overlapped with the button symbol.
This bug irritates the user easily and creates a confusion while submission.

### Screenshots

![Uploading IMG_20241107_135834 (1).jpg…]()

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/ankit071105/Ticket-Booking/blob/main/README.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by Rohan1786** [comment]
i fixed that please assign me this task  
![image](https://github.com/user-attachments/assets/f2c7a481-8176-4762-9ea6-aed93b1ad4a5)

**Comment by Rohan1786** [comment]
please assign this issue to me and review my contribution
