### ISSUE TITLE
The Javascript code is visible on the main webpage below footer

### ISSUE THREAD

**Issue by ahinagangopadhyay** [ankit071105/Ticket-Booking#109]
I want to fix this so that the JS code is not appearing on the webpage.
Please assign me this issue under Hacktoberfest 2024 and GSSOC Extended 2024
![Screenshot (257)](https://github.com/user-attachments/assets/398f3345-283d-4abf-b430-23e9538f786e)

**Comment by ahinagangopadhyay** [comment]
The code of JS is no longer appearing now in the live link .The issue seems to be fixed.

**Comment by ankit071105** [comment]
> The code of JS is no longer appearing now in the live link .The issue seems to be fixed.

okay i am assigning this issue to you. @ahinagangopadhyay
