### ISSUE TITLE
Model Schema [ Bus and train]

### ISSUE THREAD

**Issue by KrishChothani** [ankit071105/Ticket-Booking#114]
# Ticket Model Schema

## Overview
The `Bus Ticket and Train ` model represents a ticket for events in our ticket booking system.

## Purpose
To manage ticket bookings, enabling user queries and maintaining booking integrity.

## Next Steps
Implement the schema in the backend and integrate with user and event models.

**Comment by KrishChothani** [comment]
Hey @ankit071105,

I would like to work on the ticket booking model schema, especially focusing on the backend implementation. Please assign this task to me.

Thank you!

**Comment by ankit071105** [comment]
> Hey @ankit071105,
> 
> I would like to work on the ticket booking model schema, especially focusing on the backend implementation. Please assign this task to me.
> 
> Thank you!

what task do you perform i want that you can perform a task in backend of storing data's like if an user want to sell the ticket that ticket get stored and then get implement in the buy option and show in the buy.html file . If you can perform this task then i will assign this issue to you  with gssoc-extend ,lvl 3 and hacktober fest 2024

**Comment by saurabhvybs** [comment]
@ankit071105 assign this to me as i m already working on backend it is just 5 min work...soon i will raise a PR once it is Done.

**Comment by KrishChothani** [comment]
can I work on this ?
then Please assign me.
I will give you Model Schema for Bus and Train [ for level-2 ] and with controller [ for level-3] { Like Add bus-Ticket Detail, get Bus-Ticket Details, and also for Train and other controlers ....}

**Comment by KrishChothani** [comment]
Hey @ankit071105 
please tell me about this .
