### ISSUE TITLE
changing navbar 

### ISSUE THREAD

**Issue by AnkushUjawane** [ankit071105/Ticket-Booking#116]

**Comment by AnkushUjawane** [comment]
assign me 
i change navbar design

**Comment by AnkushUjawane** [comment]
i make attractive and responsive

**Comment by ankit071105** [comment]
> i make attractive and responsive

okay let me show  some demo video or pic that what did you actually want to perform. @AnkushUjawane

**Comment by AnkushUjawane** [comment]
@ankit071105 lets work together

**Comment by AnkushUjawane** [comment]
![design](https://github.com/user-attachments/assets/878e52e9-ef43-4c5b-9c70-f9393362b619)
@ankit071105 click on this link , my dem pic

**Comment by AnkushUjawane** [comment]
@ankit071105 are you assign me task 
so that i work on that 
and also solve bug of your web page
