### ISSUE TITLE
Enhancement: Redesign of "Buy Tickets" Page

### ISSUE THREAD

**Issue by SumitSahu44** [ankit071105/Ticket-Booking#119]
Description:  The current "Buy Tickets" page can be enhanced to improve user experience and functionality. The button to show available tickets is not clearly visible, and the layout could be more intuitive. I propose creating a new, user-friendly design for the "Buy Tickets" page, ensuring better visibility and accessibility of key actions. Additionally, adding separate sections for bus and train tickets could streamline the process for users.

sa assign this issue to me under gssoc-ext with hard level so i will do my best for a single page which enhance user experience

![Screenshot (280)](https://github.com/user-attachments/assets/3e21b4f0-cd0e-441f-a3a0-eeabab1fb9d2)

**Comment by ankit071105** [comment]
> e current "Buy Tickets" page can be enhanced to improve user experience and functionality. The button to show available tickets is not clearly visible, and the layout could be more intuitive. I propose creating a new, user-friendly design for the "Buy Tickets" page, ensuring better visibility and accessibility of key actions. Additionally, adding separate sections for bus and train tickets could streamline the process for users.
> 
> sa assign this issue to me under gssoc-ext with hard level so i will do my best for a single page which enhance user experience

Show me some video or pic what changes will you to in that then i will assign you. @SumitSahu44

**Comment by SumitSahu44** [comment]
something like this : 
![05 10 2024_16 28 36_REC](https://github.com/user-attachments/assets/9d6184a2-51f4-4489-86a2-1d2d7f715af6)


is you assign this to me so please add label gssoc-ext and hard level so i can do my best

**Comment by SumitSahu44** [comment]
@ankit071105 check it i pull the code

**Comment by SumitSahu44** [comment]
@ankit071105 i completed it and pull #153  please close it
