### ISSUE TITLE
Login & Registratio page 

### ISSUE THREAD

**Issue by SumitSahu44** [ankit071105/Ticket-Booking#120]
![Screenshot (281)](https://github.com/user-attachments/assets/faeecfd3-3dcf-411a-8ad9-58020a1cea7d)
login and registration page is not good as the website so i will make it responsive with attractive design so assign this issue to me under gssoc-ext with level label

**Comment by ankit071105** [comment]
> ![Screenshot (281)](https://private-user-images.githubusercontent.com/99080079/373753399-faeecfd3-3dcf-411a-8ad9-58020a1cea7d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgwOTk1NTAsIm5iZiI6MTcyODA5OTI1MCwicGF0aCI6Ii85OTA4MDA3OS8zNzM3NTMzOTktZmFlZWNmZDMtM2RjZi00MTFhLThhZDktNTgwMjBhMWNlYTdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA1VDAzMzQxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhOTQ4MGRmZjRiMTQxMjQzZWJjOTFlMWZlMjliYzM1NjA0NzczMmUyNTVkM2FjYzVhY2NiM2FmMDM5MDEzYTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.IySkplKm1XCQD1o6BIoMlRckwQel-IiE5xyHjFfCglc) login and registration page is not good as the website so i will make it responsive with attractive design so assign this issue to me under gssoc-ext with level label

Bro @saurabhvybs  look into this the data is also not getting store i propose that add one page the data which user will provide email phone number name user name show them in that page . Create a html file name profile.html . If you can perform then response to this i will assign this to you

**Comment by SumitSahu44** [comment]
Yup i can assign this to me with gssoc-ext and level label

**Comment by saurabhvybs** [comment]
@ankit071105 data is getting stored on MongoDB just add the .env file on your end at local system....and i have not added a page where i will fetch the data from DB and make sure it is visible to the user on the frontend i m already working on it....as soon the dashboard will be finished by me i will simply integrate the api and it will show...and dont worry for the theme..once API will be integrated theme will be managed in no sec...but for now i m focusing on API integration

**Comment by ankit071105** [comment]
@ankit071105 data is getting stored on MongoDB just add the .env file on your end at local system....and i have not added a page where i will fetch the data from DB and make sure it is visible to the user on the frontend i m already working on it....as soon the dashboard will be finished by me i will simply integrate the api and it will show...and dont worry for the theme..once API will be integrated theme will be managed in no sec...but for now i m focusing on API integration

Okay  do your work bro
