### ISSUE TITLE
Enhance Hover Effects for Social Sidebar Icons

### ISSUE THREAD

**Issue by 3Sangeetha3** [ankit071105/Ticket-Booking#123]
**Problem Summary:** 
The hover functionality for the social sidebar icons is currently not visually engaging or consistent across devices. Users should experience a smooth, visually appealing hover effect that highlights each icon and improves overall user experience.

https://github.com/user-attachments/assets/cb8368ff-1f6f-4939-a588-fdf907dfa3d2

Steps to Reproduce: 
1. Navigate to the social sidebar section.
2. Navigate to the social sidebar section.
Navigate to the social sidebar section.

**Proposed Solution:** 
Improve hover effects for the social media icons (e.g., smooth transition), On hovering out making smooth transitions for icons.

Please assign me this issue under Hacktoberfest 2024 and GSSOC Extended 2024.

**Comment by ankit071105** [comment]
> **Problem Summary:** The hover functionality for the social sidebar icons is currently not visually engaging or consistent across devices. Users should experience a smooth, visually appealing hover effect that highlights each icon and improves overall user experience.
> 
>  Screen.Recording.2024-10-05.at.1.15.55.AM.mov 
> Steps to Reproduce:
> 
> 1. Navigate to the social sidebar section.
> 2. Navigate to the social sidebar section.
>    Navigate to the social sidebar section.
> 
> **Proposed Solution:** Improve hover effects for the social media icons (e.g., smooth transition), On hovering out making smooth transitions for icons.
> 
> Please assign me this issue under Hacktoberfest 2024 and GSSOC Extended 2024.

okay i am assiging this to you under gssoc-extend and  Hacktoberfest @3Sangeetha3
