### ISSUE TITLE
Google Firebase authentication while login/signup

### ISSUE THREAD

**Issue by riyaaryan2004** [ankit071105/Ticket-Booking#124]
### Description
I want to add google firebase authentication for smooth signin process without email password
I will google button for "continue with google"

### screenshot
![Screenshot 2024-10-05 014220](https://github.com/user-attachments/assets/8a8c38d9-1299-4a04-8130-72447002a793)
![Screenshot 2024-10-05 014154](https://github.com/user-attachments/assets/3d505c3a-121b-4a78-835c-5ab3c770529f)

### Checklist

- [x]  I have checked the existing issues
- [x]  I have read the [Contributing Guidelines](https://github.com/ankit071105/Ticket-Booking/tree/main/README.md)
- [x]  I'm a GSSoC'24-Extd contributor
- [x]  I'm a Hacktoberfest'24 contributor
- [x]  I am willing to work on this issue (optional)

**Comment by ankit071105** [comment]
> ### Description
> I want to add google firebase authentication for smooth signin process without email password I will google button for "continue with google"
> 
> ### screenshot
> ![Screenshot 2024-10-05 014220](https://private-user-images.githubusercontent.com/145834658/373796970-8a8c38d9-1299-4a04-8130-72447002a793.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgxMDA2OTMsIm5iZiI6MTcyODEwMDM5MywicGF0aCI6Ii8xNDU4MzQ2NTgvMzczNzk2OTcwLThhOGMzOGQ5LTEyOTktNGEwNC04MTMwLTcyNDQ3MDAyYTc5My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwNVQwMzUzMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZTFkOTg4NGE1MDIwNDkyOGJjNTg5OTgyNTJjZjlhNTkxZWU1YTYwNjg0OTgyMjI4MjcwMTg0NWYwNzQ0YmQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.h6eyK_w1yWTuUrQvGgq9U1Ma9qi4sLTVdApERgISJwk) ![Screenshot 2024-10-05 014154](https://private-user-images.githubusercontent.com/145834658/373796997-3d505c3a-121b-4a78-835c-5ab3c770529f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgxMDA2OTMsIm5iZiI6MTcyODEwMDM5MywicGF0aCI6Ii8xNDU4MzQ2NTgvMzczNzk2OTk3LTNkNTA1YzNhLTEyMWItNGE3OC04MzVjLTVhYjNjNzcwNTI5Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwNVQwMzUzMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMGVlMGQ0Yjg4ZGJmYTU0NjQzZTg5N2QxMTUxY2E0ZDVjNjlhMzg5ZTU3MWFlNDI0Y2NhZWIwOTQwODI5MDljJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.EBz_tqodaigep2qcIxjIquaxZT1YFoBuJJb2apdnpHQ)
> 
> ### Checklist
> * [x]   I have checked the existing issues
> * [x]   I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
> * [x]   I'm a GSSoC'24-Extd contributor
> * [x]   I'm a Hacktoberfest'24 contributor
> * [x]   I am willing to work on this issue (optional)

okay i want to add one more thing add facebook option to with meta developers option .Okay i am assiging this i hope you will perform both front end and backend in a better way.

**Comment by riyaaryan2004** [comment]
Thank You for assigning .I am working on that .

**Comment by riyaaryan2004** [comment]
@ankit071105 
Implementation is done .
please provide me google firebase credential of your firebase project.
Please ensure that Google sign in is enabled.
I have checked with my temporary firebase project and it is working.

### Example Screenshot
![Screenshot 2024-10-05 125443](https://github.com/user-attachments/assets/ed31ca25-4462-4d32-8396-600c4e7c1fd4)
![Screenshot 2024-10-05 125641](https://github.com/user-attachments/assets/0a170e40-5094-46f0-816f-f920f2c762a5)

**Comment by riyaaryan2004** [comment]
@ankit071105
 I will raise a PR as soon as you provide me credential.
I am waiting for this only.

**Comment by ankit071105** [comment]
> @ankit071105 Can u provide the firebase credential or should I raise PR with blank credentials.. Please confirm.

I will provide in your linkedin profile before the night .I was travelling so i was unable to do this

**Comment by ankit071105** [comment]
> Okay! @ankit071105 please ensure google, facebook, email/password options are enabled in authorization section of firebase console.

I have send you message in linkedin see that and reply me there
