### ISSUE TITLE
Buttons are not aligned 

### ISSUE THREAD

**Issue by Anshuaman2001** [ankit071105/Ticket-Booking#126]
buttons are at different positions from each other.
![Screenshot 2024-10-05 032733](https://github.com/user-attachments/assets/fa9f3cd9-1399-4d6b-a3c8-aa93b4ca36f2)

**Comment by Anshuaman2001** [comment]
i am a gssoc extended and Hactobefest contributor

**Comment by ankit071105** [comment]
> i am a gssoc extended and Hactobefest contributor

it has been resolved now i have assigned this one.
