### ISSUE TITLE
Cancellation & Refund Tracker

### ISSUE THREAD

**Issue by meghanakn473** [ankit071105/Ticket-Booking#127]
I want to implement this feature so that users can manage cancellations and track refund status directly from their profile.

**Comment by meghanakn473** [comment]
hey @ankit071105 can u assign me this issue i want to work on it

**Comment by ankit071105** [comment]
> hey @ankit071105 can u assign me this issue i want to work on it

there is not need for this our website is working for them only . If an user want to cancel there ticket then he can sell that to us we will give back them good refund and buyer will also have to pay less then the tacktal one  @meghanakn473  . I am closing this
