### ISSUE TITLE
update NavBar UI/UX

### ISSUE THREAD

**Issue by ABHI-SHEK-001** [ankit071105/Ticket-Booking#134]
nav-bar items are not allign and also not matching with your theme. i want to update it. 
![Screenshot 2024-10-05 115746](https://github.com/user-attachments/assets/47ae8a5c-4ef2-463e-9548-cb7910060f7b)

**Comment by vk-cse** [comment]
@ankit071105 your navbar is not matching with the theme and also it is not looking much better, can you assign it to me. I'll fix this issue
