### ISSUE TITLE
Redesign Logo/fevicon

### ISSUE THREAD

**Issue by CharVaibhav** [ankit071105/Ticket-Booking#136]
Hey ankit,

As a GSSoc contributor I would like to redesign your logo/fevicon, as logo acts as identity to your website and it has it be perfect, as the current one is unclear and hard to identify i would like to take the opportunity to design and update it.

![Screenshot 2024-10-05 121847](https://github.com/user-attachments/assets/93004958-3b30-4c32-b9ce-e50e03a41ef0)

**Comment by Ananya-vastare** [comment]
I am a gssoc contributor I would like to work with this issue

**Comment by Ananya-vastare** [comment]
![Change7](https://github.com/user-attachments/assets/cdd9626a-c495-427c-9328-1d4891cdf705)
This is the new look of the website as it blends really well with the color palette of the website and its theme

**Comment by Ananya-vastare** [comment]
@ankit071105 may I please know whether it will be merged or not

**Comment by ankit071105** [comment]
> @ankit071105 may I please know whether it will be merged or not

Have you generated a PR @Ananya-vastare

**Comment by Ananya-vastare** [comment]
Yes I have

**Comment by ankit071105** [comment]
Okay send me your pr number I will merge it and issue number to

**Comment by Ananya-vastare** [comment]
f713a70 is my pr number
