### ISSUE TITLE
password show button

### ISSUE THREAD

**Issue by riyaaryan2004** [ankit071105/Ticket-Booking#138]
### Issue 
User don't have option to see whether they have enter correct or wrong password by mistake.

### Solution
I want to add password toggle button in password section of both login and signup form .  

### Screenshots
![Screenshot 2024-10-05 131218](https://github.com/user-attachments/assets/ea532181-540a-48ae-8b3b-09b0d8c563c7)

### Checklist

- [x]  I have checked the existing issues
- [x]  I have read the [Contributing Guidelines](https://github.com/ankit071105/Ticket-Booking/tree/main/README.md)
- [x]  I'm a GSSoC'24-Extd contributor
- [ ]  I'm a Hacktoberfest'24 contributor
- [x]  I am willing to work on this issue (optional)

**Comment by Meera-Singh26** [comment]
@ankit071105 assign me this project
