### ISSUE TITLE
Idea: Make the FAQ Details and Summary have a little animation when clicked.

### ISSUE THREAD

**Issue by sarinsanyal** [ankit071105/Ticket-Booking#143]
![Screenshot 2024-10-05 170555](https://github.com/user-attachments/assets/d071f42b-c860-43d6-8b07-ab0be141e58e)

In the FAQ section, whenever a detail is clicked for the drop-down hidden text, we can implement a little slow animation down to make it look interesting, instead of it all appearing at once.

@ankit071105 please assign me this. Also, please do add Hacktoberfest and GSSoC Extended labels. Thank you!

**Comment by khushi-20-cse** [comment]
Respected Sir,
              May!..I give this questions answer

**Comment by ankit071105** [comment]
> Respected Sir, May!..I give this questions answer

yes you can

**Comment by khushi-20-cse** [comment]
Thank you for your response.
