### ISSUE TITLE
ATTENTION EVERYONE !!!!!!!

### ISSUE THREAD

**Issue by ankit071105** [ankit071105/Ticket-Booking#148]
I have seen the deploy link the Js code is not working in any of the page . Resolve all the contributor those who are intreseted and can resolve mention your that you can easily handle without creating any issue. Then the ticket should be shown in the buy page which will be sold in the sell page . Resolve the issue .

**Comment by ankit071105** [comment]
> I have seen the deploy link the Js code is not working in any of the page . Resolve all the contributor those who are intreseted and can resolve mention your that you can easily handle without creating any issue. Then the ticket should be shown in the buy page which will be sold in the sell page . Resolve the issue .

ANYONE WANT TO SOLVE THIS ISSUE WORK ON THIS .

**Comment by Arnab7456** [comment]
working on it , assign it to me

**Comment by SumitSahu44** [comment]
hey @ankit071105 assign this to me i will make complete site responsive , working js , and fix minor issue

**Comment by SumitSahu44** [comment]
hey @ankit071105 i working  on it can you tell me more what you are expecting

**Comment by SumitSahu44** [comment]
hey @ankit071105 please don't assign same work for others they mess-up all code and which is good before assigning them

**Comment by SumitSahu44** [comment]
hey @ankit071105 add labels so it can help me to collect points
