### ISSUE TITLE
To change twitter logo to X logo

### ISSUE THREAD

**Issue by Pavan8421** [ankit071105/Ticket-Booking#150]
## I want to change twitter handle logo to X logo

![Screenshot 2024-10-05 214426](https://github.com/user-attachments/assets/65b715fd-c09c-4c5e-b077-80a1af644ce5)

## Please assign me this issue under gssoc-ext and hacktoberfest

**Comment by rupeshv2121** [comment]
I'm glad , please this task under gssoc-ext and hacktoberfest
