### ISSUE TITLE
Changes in Contact Us

### ISSUE THREAD

**Issue by neeru24** [ankit071105/Ticket-Booking#152]
Hi, While exploring, I came across this bug that you've not added anything in the contact us section...... There is lorem ipsum boiler plate code over there...

I want to modify it with something engaging. Kindly assign me this issue.

![image](https://github.com/user-attachments/assets/11a70f6e-bdf5-4490-8556-4c947f725e94)

**Comment by neeru24** [comment]
> Hi, While exploring, I came across this bug that you've not added anything in the contact us section...... There is lorem ipsum boiler plate code over there...
> 
> I want to modify it with something engaging. Kindly assign me this issue.
> 
> ![image](https://github.com/user-attachments/assets/11a70f6e-bdf5-4490-8556-4c947f725e94)
> 

@ankit071105 Can you please assign the labels too for GSSoC & any level of your wish 🙏

**Comment by neeru24** [comment]
> > Hi, While exploring, I came across this bug that you've not added anything in the contact us section...... There is lorem ipsum boiler plate code over there...
> > 
> > I want to modify it with something engaging. Kindly assign me this issue.
> > 
> > ![image](https://github.com/user-attachments/assets/11a70f6e-bdf5-4490-8556-4c947f725e94)
> > 
> 
> @ankit071105 Can you please assign the labels too for GSSoC & any level of your wish 🙏

Hey, I want to ask one thing... It could be a common question to ask but still... After forking it and making the required changes, I have to open a PR... Is it the same for this too? I just want to confirm once. 

Thank you :)

**Comment by Samar-Ali-Ansari** [comment]
On hovering the Contact us section the text disappears
I'll be correcting this issue
kindly assign me the issue [GSSOC,-ext , Hacktober]
@ankit071105
