### ISSUE TITLE
Unresponsive SideBar Toggle

### ISSUE THREAD

**Issue by irfanbroo** [ankit071105/Ticket-Booking#154]
![Screenshot (99)](https://github.com/user-attachments/assets/76f3e546-6a4a-44b6-914b-aff8f4cfbdf6)
The Side Bar Toggle is unresponsive and needs to be improved upon.
I am glad to work upon this and fixing it

**Comment by Targter** [comment]
Issues:
- The sidebar toggle is unresponsive, negatively affecting user experience.
- Users cannot easily access the sidebar, making navigation cumbersome.

Solution:
- I will enhance the functionality of the sidebar toggle, ensuring it responds quickly and smoothly to user interactions.
- This will improve navigation and overall user experience.

@ankit071105  Please assign this issue to me and add the labels for **GSSoC-EXT** and **Hacktoberfest**.
