### ISSUE TITLE
[BUG] : Dark Theme Toggle Button Not Working

### ISSUE THREAD

**Issue by rudrapratap63** [ankit071105/Ticket-Booking#161]
The dark theme toggle button is not functioning as expected. When clicked, it does not switch the theme from light to dark or vice versa. This issue affects the user experience, as users are unable to utilize the dark mode feature.

### Expected Behavior:
- The toggle button should switch the theme between light and dark modes seamlessly.
- The change should be reflected immediately without any delay or glitches.

### Steps to Reproduce:
1. Open the application.
2. Click on the dark theme toggle button.
3. Observe that the theme does not change.

![image](https://github.com/user-attachments/assets/532d8c34-d85a-46c0-abca-a126c8f0e7a6)

**Comment by pranavmugatkar** [comment]
Hi @rudrapratap63, can i take the issue
