### ISSUE TITLE
 The sell.html page requires UI improvements to enhance user experience and visual consistency.

### ISSUE THREAD

**Issue by Arnab7456** [ankit071105/Ticket-Booking#168]
let me assign this issue, its my pleasure to work on it
want to fix that page 

![Screenshot 2024-10-06 130122](https://github.com/user-attachments/assets/2243f78d-e30c-4e5f-a4e7-340b6267f6d2)

**Comment by ankit071105** [comment]
> let me assign this issue, its my pleasure to work on it want to fix that page
> 
> ![Screenshot 2024-10-06 130122](https://private-user-images.githubusercontent.com/93949960/373929605-2243f78d-e30c-4e5f-a4e7-340b6267f6d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyMDA2ODgsIm5iZiI6MTcyODIwMDM4OCwicGF0aCI6Ii85Mzk0OTk2MC8zNzM5Mjk2MDUtMjI0M2Y3OGQtZTMwYy00ZTVmLWE0ZTctMzQwYjYyNjdmNmQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA2VDA3Mzk0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0OTFhOGU4ZWZhMjE1NmYwODBjZTIzNDliZDRjN2Y5MjUzMzI2MjJiMzZiMzQyMmE5MjhiNTJkYWQwZDNiODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.RufUehvD1U3jlqwf2iwHmHrmULMPhiP-mZG1C8zDcJY)

it requires the js code is also not working into this if you can both i can assign under gssoc-ext hacktoberfest and with lvl

**Comment by Arnab7456** [comment]
ok i will fix both, assign it to me
