### ISSUE TITLE
Ask for source and  destination for buying tickets and display suitable tickets

### ISSUE THREAD

**Issue by ash-k121** [ankit071105/Ticket-Booking#17]
![image](https://github.com/user-attachments/assets/88db86e3-0da2-45d4-83bd-d2512face5d1)

**Comment by ankit071105** [comment]
what you want to contribute in this

**Comment by ash-k121** [comment]
If a user selects bus tickets it will display all the tickets but we only need the tickets from the source to destination .We can add a filter here .
