### ISSUE TITLE
Missing requirement for purchasing the ticket

### ISSUE THREAD

**Issue by Mansi-Tanwar** [ankit071105/Ticket-Booking#176]
![image](https://github.com/user-attachments/assets/7ef6dab2-30de-4a17-ae77-f610c73ebf60)

In this it is mentioned that who wants to buy the ticket, which ticket and how many tickets but to book the tickets important thing is from where to where. That question is missing in the form. 

![image](https://github.com/user-attachments/assets/eae0959e-5a41-4d10-be9e-bccb3a26a61c)
Along with that interface to sell tickets is also different from buy tickets. The website will look better if the interfaces for both are same. I would love to work on this issue if you will assign this task to me.

**Comment by SumitSahu44** [comment]
@ankit071105 asssign this to me because i done the buy ticket page work so i know all the code structure and i can easily make a selling ticket page also with all detailling

**Comment by Mansi-Tanwar** [comment]
The code structure is quite easy to understand. I can also do that with ease and detailing. So, it won't be an issue if you assign this task to me too. Thank you.
