### ISSUE TITLE
Adding All Contributors Profile Photos in Readme.md file

### ISSUE THREAD

**Issue by say-het** [ankit071105/Ticket-Booking#18]
### **Issue Description**

 - It lacks Contributors Profiles in Readme.md
 - It should be Like the image that I have shared
 - Hey! @ankit071105 I have already fixed it. Can you assign me this issue under GSSoC-Extd and Hacktoberfest so that I can raise a PR.

 - Little about me: I am an experienced contributor as I have successfully completed Hacktoberfest-2020, Hacktoberfest-2023 and GSSoC-2024.

 **I will add this type of Live Contributor Profile Photos in it**
![image](https://github.com/user-attachments/assets/c109d3d6-a375-493e-a01b-aaf9370d603c)

**Comment by say-het** [comment]
Why did you close the Issue?

**Comment by ankit071105** [comment]
> Why did you close the Issue?

I have assigned the issue  to you provide me the solution and i will closed the issue . Generate PR
