### ISSUE TITLE
Social icon update 

### ISSUE THREAD

**Issue by Antima2004** [ankit071105/Ticket-Booking#180]
Fix the social media icon e. g. Twitter
![Screenshot_2024-10-06-17-46-27-97_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/aa6daf53-45fa-455a-bb44-638e20e027d1)
Please assign this to me and add label on this issue.

**Comment by ankit071105** [comment]
Not needed
