### ISSUE TITLE
There is no Footer section

### ISSUE THREAD

**Issue by satyasootar** [ankit071105/Ticket-Booking#181]
**Proposal**
I want to add a deicated footer to the page.

**Expected Outcome**
The page will look more professional

**Comment by ankit071105** [comment]
> **Proposal** I want to add a deicated footer to the page.
> 
> **Expected Outcome** The page will look more professional

suggest some demo ss and video @satyasootar

**Comment by satyasootar** [comment]
![image](https://github.com/user-attachments/assets/bbaa14d1-da4d-4520-99f4-dfd58cb97741)

***Taking the reference from the above image***
- I can built the footer using the theme of the Ticket Booking
- I can add dummy links which can be super useful in future while scaling the website

**Comment by satyasootar** [comment]
Please add the labels otherwise my pr will not shown on the leaderboard @ankit071105
