### ISSUE TITLE
fix home page cards for mobile view

### ISSUE THREAD

**Issue by jainaryan04** [ankit071105/Ticket-Booking#192]
please add gssoc and hacktoberfest labels.

![image](https://github.com/user-attachments/assets/657e484e-c8bd-4ca4-8c4d-6e030637bb5d)

**Comment by shrutilad20** [comment]
please assign to me
under gssoc and hactoberfest

**Comment by jainaryan04** [comment]
@ankit071105 

can you fix this ? maybe adding hacktoberfest tag to the repository will fix it ?
![image](https://github.com/user-attachments/assets/ea86bb6b-17ac-4753-9648-f4666b5ebea8)
