### ISSUE TITLE
Improve the navabar of the page

### ISSUE THREAD

**Issue by jayanththalla** [ankit071105/Ticket-Booking#2]
In the navbar by adding the icon and the logo of the page make it attractive

**Comment by ankit071105** [comment]
> In the navbar by adding the icon and the logo of the page make it attractive

you want to do ?

**Comment by jayanththalla** [comment]
> > In the navbar by adding the icon and the logo of the page make it attractive
> 
> you want to do ?

Adding logo and improve the navbar by the icons and symbol

**Comment by surajgoraicse** [comment]
Can I work on this same issue. I will use a custom logo and improve the navbar by making it responsive and attractive.

**Comment by ankit071105** [comment]
> Can I work on this same issue. I will use a custom logo and improve the navbar by making it responsive and attractive.

Go for it
