### ISSUE TITLE
Add Coupons and discounts

### ISSUE THREAD

**Issue by poorvikaa08** [ankit071105/Ticket-Booking#20]
Add a Coupon Code Section:-
Include a dedicated input field labeled "Apply Coupon?" where users can enter their discount or promotional code.
 
Real-Time Discount Application:-
* Real-Time Feedback: After applying the coupon code, show immediate feedback such as:
    >> A success message if the coupon is valid, with the discount amount or percentage displayed.
    >>An error message if the code is invalid or expired.
* Total Price Update: Dynamically adjust and update the total price once the coupon code is applied, showing the discount subtracted from the total.

Example Workflow
1. Input: User enters the coupon code in the input field.
2. Apply: User clicks the "Apply" button.
3. Validation: The coupon is validated via the backend.
4. Feedback: The system returns either a success message (with updated pricing) or an error if the coupon is invalid.
5. Final Total: The total cost reflects the discount, and the user can proceed with the payment.

Screenshot 📸 
![image](https://github.com/user-attachments/assets/88f03b0b-0166-4af9-a65d-ddc2966878f5)

@ankit071105 Would you assign this issue to me under gssoc24 extd and hacktoberfest with appropriate level?

**Comment by ankit071105** [comment]
Sorry but we cannot offer any discount because we have are acting as middle one between buyer and seller
