### ISSUE TITLE
Add date of journey

### ISSUE THREAD

**Issue by shalini-bhandari** [ankit071105/Ticket-Booking#209]
Improvement of Bus journey Buy ticket form by adding Date of journey.
@ankit071105 kindly assign me this issue under gssoc-ext and hacktoberfest-accepted with appropriate level.

<img width="1280" alt="Screenshot 2024-10-07 at 10 40 25" src="https://github.com/user-attachments/assets/7e757b94-7a93-40b3-a09b-7df31e35075f">

**Comment by ankit071105** [comment]
If you are performing this then add the time destination  and depature too add time date , locations @shalini-bhandari

**Comment by shalini-bhandari** [comment]
> If you are performing this then add the time destination and departure too add time date , locations @shalini-bhandari

Sure, I will add the following :
1. Date of Journey
2. Time of departure
3. Destination for bus journey
