### ISSUE TITLE
 Users unable to register or log in due to error while fetching response

### ISSUE THREAD

**Issue by an-um** [ankit071105/Ticket-Booking#213]
Users are encountering an error when attempting to register or log in. The issue occurs when fetching the response from the server, resulting in unsuccessful sign-ins. This issue blocks users from accessing their accounts and prevents them from successfully registering. 

**Expected Behavior:**
Users should be able to successfully register or log in and receive a proper response from the server, allowing them access to the application.

**Actual Behavior:**
An error occurs when fetching the response, causing the login or registration to fail. No success message is displayed, and users remain on the login/register page.

Please assign this task to me under **Hectoberfest-accepted and gssoc-ext.** 

<img width="1063" alt="image" src="https://github.com/user-attachments/assets/78dd665b-e3d1-4f72-8f00-66dedb63faab">

**Comment by an-um** [comment]
@ankit071105 please assign this task to me

**Comment by ankit071105** [comment]
@saurabhvybs  Resolve this bro . Issue are creating in the code .

**Comment by an-um** [comment]
@ankit071105 please assign this to me, as I created this issue and have searched how to solve it. Please assign this to me under hectoberfest
