### ISSUE TITLE
update nav bar

### ISSUE THREAD

**Issue by Ek-ta-bharti** [ankit071105/Ticket-Booking#218]
![Screenshot 2024-10-07 185143](https://github.com/user-attachments/assets/36643e72-64f0-4ff2-9b55-52f3ee1f2190)
Hey, the navigation bar is not responsive. Can you please assign me to fix this issue?

**Comment by sanjeev0304** [comment]
Could you assign me to resolve the issue with the unresponsive navigation bar?
