### ISSUE TITLE
BUG: No standard for PASSWORD and PHONE NUMBER

### ISSUE THREAD

**Issue by sindhuja184** [ankit071105/Ticket-Booking#222]
There is no standard for password and issue.

If I am assigned this task I would add standard for password and phone number.

In password section I can add standards like minimum length of the password, no sequence of character, the password combination of lower and upper case letter, numbers and special characters.

We can validate the phone number.

Thanks @ankit071105

**Comment by ankit071105** [comment]
Backend team is working on it already assigned this issue to them @saurabhvybs  see this.
