### ISSUE TITLE
Footer Links and Check  Availability button is  Not Functioning

### ISSUE THREAD

**Issue by simmi-verma** [ankit071105/Ticket-Booking#227]
![Screenshot (1067)](https://github.com/user-attachments/assets/770d5a1d-64c0-41f9-a2f5-a3cafa8f3cce)
The links in the footer section are not working, and the "Check Availability" feature is also unresponsive. Please look into this issue.
 please assign to me .I would like to work on that

**Comment by ankit071105** [comment]
Not required we have added dummy items we will attached the link backend team is working in that
