### ISSUE TITLE
 Website Not Responsive

### ISSUE THREAD

**Issue by simmi-verma** [ankit071105/Ticket-Booking#228]
![Screenshot (1068)](https://github.com/user-attachments/assets/a02dd8f3-63e6-43ff-a1a8-4a181c14b6f2)

The website is not displaying correctly on different screen sizes, making it difficult to navigate on mobile and tablet devices. Please investigate the responsiveness issue.
I would like to work on that please assign to me.

**Comment by simmi-verma** [comment]
Header section need to improve so I can solve that also.

**Comment by ankit071105** [comment]
assigned and completed
