### ISSUE TITLE
Changing the UI of ticket booking 

### ISSUE THREAD

**Issue by saloni911** [ankit071105/Ticket-Booking#233]
<img width="600" alt="img" src="https://github.com/user-attachments/assets/37d0ccdb-6a10-41d1-ada2-c71b77958426">we
We can retain this design and color theme as it looks visually appealing and modern. This aesthetic can help attract and engage users, ultimately driving more traffic to the website. The vibrant and cohesive design will not only enhance the user experience but also encourage users to explore further, making the website more attractive to visitors.
<img width="387" alt="colour theme" src="https://github.com/user-attachments/assets/c3310a50-a893-46b1-a9fc-106f6e1a47da">

**Comment by shrutilad20** [comment]
assign me this task

**Comment by saloni911** [comment]
@ankit071105 We propose redesigning the footer of the website to include a section for a newsletter signup. This update will not only modernize the look of the footer but also increase engagement by encouraging visitors to subscribe for updates and news.

Proposed Functionality:

Add a newsletter signup form in the footer, featuring an email input field and a clear "Subscribe" button.
Update the footer design to be more modern, with better spacing, typography, and alignment for existing footer elements (e.g., social media links, copyright information, quick links).
Ensure the newsletter signup is responsive and fits well within the overall footer design on both desktop and mobile views.
Include a brief call to action encouraging users to subscribe (e.g., "Stay updated with the latest news and events").
![374277038-5ea2d045-e138-4f0f-8680-2648c784cf1c](https://github.com/user-attachments/assets/389f3839-f2c3-4c65-93e6-7070485c4c68)

**Comment by ankit071105** [comment]
not required
