### ISSUE TITLE
Enhance "Why Book With Us" Section & Improve Responsiveness

### ISSUE THREAD

**Issue by Snehagiri554** [ankit071105/Ticket-Booking#240]
*I would like to enhance the "Why Book With Us" section.
*Improve design and add responsiveness.
*Ensure it adapts to different screen sizes.
*Add visual enhancements: hover effects and animations for a better user experience.
Could you please assign me this? @ankit071105 
![Screenshot 2024-10-08 013102](https://github.com/user-attachments/assets/342224a1-5674-46e8-a17a-dbe2475a073a)

![image](https://github.com/user-attachments/assets/f0bcac4f-ea4a-497b-91be-2cb97106e7c9)

**Comment by ankit071105** [comment]
Front end team is working in this and fixing the issue if you can show me some demo solution then i can assigned this to you. @Snehagiri554

**Comment by ankit071105** [comment]
Dont change uncessary file and not add any other code resolve the issue and bug and generate the pr @Snehagiri554
