### ISSUE TITLE
Text Alignment and Nav-Bar Alignments I want to fix this

### ISSUE THREAD

**Issue by rahulkumarparida** [ankit071105/Ticket-Booking#242]
# Under Gssoc 2024-Extd
**I want to fix the nav alignments**
![Screenshot 2024-10-08 081839](https://github.com/user-attachments/assets/f24335ec-642f-4adc-b58b-77556f8cf8cf)
**and also text alignments in**
![Screenshot 2024-10-08 081347](https://github.com/user-attachments/assets/58e220a2-49e9-4d59-b144-8f3678abde51)
**Please This will be first open source contribution**

**Comment by ankit071105** [comment]
Not required

**Comment by rahulkumarparida** [comment]
> Not required
Please
