### ISSUE TITLE
[Feature] Chatbot

### ISSUE THREAD

**Issue by shalini-bhandari** [ankit071105/Ticket-Booking#247]
Addition of chatbot will be helpful for users as it will work as helpdesk that will solve queries and provide information.
@ankit071105 Kindly assign me this issue under gssoc-ext and hacktoberfest-accepted with level3
Regards.

**Comment by ankit071105** [comment]
> Addition of chatbot will be helpful for users as it will work as helpdesk that will solve queries and provide information. @ankit071105 Kindly assign me this issue under gssoc-ext and hacktoberfest-accepted with level3 Regards.

chat bot is there but it is not responding will you able to handle it backend code if yes then i will assigned this issue to you.

**Comment by shalini-bhandari** [comment]
> > Addition of chatbot will be helpful for users as it will work as helpdesk that will solve queries and provide information. @ankit071105 Kindly assign me this issue under gssoc-ext and hacktoberfest-accepted with level3 Regards.
> 
> chat bot is there but it is not responding will you able to handle it backend code if yes then i will assigned this issue to you.

Yes assign me
