### ISSUE TITLE
Enhancing the Why book with us section , About us anchor tag and contact us form

### ISSUE THREAD

**Issue by ankushnaudiyal09** [ankit071105/Ticket-Booking#248]
1-> Why book with us Section overlap into the footer and set a bad user experience . 

![Screenshot 2024-10-08 114512](https://github.com/user-attachments/assets/8e6482dc-951a-4e7c-a9f0-b9c5778ad403)

Assign me the task and i will definitely make it better than previous . 

2-> the second about us will not directed to any web page , in short it doesn't make anything happen , so basically it is useless . 

![Screenshot 2024-10-08 114728](https://github.com/user-attachments/assets/f9791c0a-ec7d-44b3-8350-0897a1cc8faa)

3-> when user hovers on the heading of contact us form  , it changes its color and the color used in this hover effect is useless , the heading seems to be invisible 

![Screenshot 2024-10-08 114636](https://github.com/user-attachments/assets/95dc5ede-015d-4797-96e7-53063ca2bee1)

Assign me the task , I will make changes which definitely looks better . @ankit071105

**Comment by ankit071105** [comment]
resolved this one
