### ISSUE TITLE
About Us Feature Not Functional

### ISSUE THREAD

**Issue by Saaarthak0102** [ankit071105/Ticket-Booking#249]
### Description

I noticed that the "About Us" section on the website is currently not functional. When users attempt to access it, they are either met with an error message or redirected to a different page.

### Screenshots

![image](https://github.com/user-attachments/assets/635e606c-a9b8-4b96-9bb2-a982f7acc626)

### Any additional information?

The "About Us" section should load and provide relevant information about the project/team.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/ankit071105/Ticket-Booking/blob/main/README.md)
- [X] I'm a GSSoC'24-Extd contributor
- [ ] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by ankit071105** [comment]
Resolve bro
