### ISSUE TITLE
Home page is not Responsive 

### ISSUE THREAD

**Issue by saurabhvybs** [ankit071105/Ticket-Booking#25]
if you allow me to use Tailwind i can just fix this up

**Comment by INam1995** [comment]
hey @ankit071105 
can you please assign it to me?
#gssoc-ext 2024

**Comment by ankit071105** [comment]
> hey @ankit071105 can you please assign it to me? #gssoc-ext 2024
@INam1995 
bro already assign raise an new issue exisiting issue has been assigned to the following people

**Comment by SumitSahu44** [comment]
hey @ankit071105 i solved this issue with PR number :  #243 so assign this to me and close it with labels
