### ISSUE TITLE
Homepage UI is not consistent

### ISSUE THREAD

**Issue by Saaarthak0102** [ankit071105/Ticket-Booking#250]
### Description

I've observed some inconsistencies in the homepage UI that need attention:

Navigation Bar: The navigation bar includes extra buttons, specifically "About Us" and the "Mode Change" button. This can lead to confusion for users as it deviates from the expected navigation flow.

"Why Book with Us" Formatting: The "Why Book with Us" section is not formatted consistently with the rest of the page, which affects the overall user experience.

### Screenshots

![image](https://github.com/user-attachments/assets/2204c3a3-7f29-4bf4-9ac7-8d48c5f3e82b)
![image](https://github.com/user-attachments/assets/c536db4b-d83a-4bb7-8b5d-584aa28637dd)

### Any additional information?

1)The navigation bar should have a streamlined set of buttons that align with the website's purpose.
2)The formatting of the "Why Book with Us" section should be consistent with other sections on the homepage.

Addressing these issues will enhance the overall user experience and maintain a cohesive design throughout the website.

Thank you!

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/ankit071105/Ticket-Booking/blob/main/README.md)
- [X] I'm a GSSoC'24-Extd contributor
- [ ] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by ankit071105** [comment]
Already resolved
