### ISSUE TITLE
[BUG] To remove extra mode changing symbols

### ISSUE THREAD

**Issue by 23wh1a0513** [ankit071105/Ticket-Booking#251]
### Description

There are extra symbols for toggling between light mode and dark mode on a website. Typically, clicking on the moon icon switches to dark mode, while clicking on a sun or similar icon would switch back to light mode. It's a common feature for adjusting the website's theme to suit lighting preferences.

### Screenshots

(https://github.com/user-attachments/assets/fdc15a03-f5c0-4b46-a753-88d8407b9ed7)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/ankit071105/Ticket-Booking/blob/main/README.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by ankit071105** [comment]
Resolved bro you can check now

**Comment by 23wh1a0513** [comment]
Yes it has been changed.
