### ISSUE TITLE
Modification of Twitter logo to "X".

### ISSUE THREAD

**Issue by Lokesh11868** [ankit071105/Ticket-Booking#259]
The Twitter Logo has to be Modified to current logo "X".

could you please assign me this issue under gssoc'24 ext. with suitable level?

**Comment by aryangaur380** [comment]
Dear @ankit071105 ,

I hope you're doing well. I would like to request this project assignment to contribute to. I'm eager to get involved and apply my skills to make a meaningful impact.

Looking forward to your response.

Best regards,  
Aryan Gaur
