### ISSUE TITLE
Can add hover effect on email us and Chat on Whatsapp

### ISSUE THREAD

**Issue by Geet2002** [ankit071105/Ticket-Booking#26]
Darken the color of the buttons Email Us an Chat on WhatsApp on the footer. And can add hovering effect also. Assign this to me i will make it.

**Comment by Krishnamverma951** [comment]
can you please assign this issue

**Comment by ankit071105** [comment]
> can you please assign this issue

it is not needed raise any other issue work on the backend part

**Comment by Krishnamverma951** [comment]
can i do this or not

**Comment by ankit071105** [comment]
> can i do this or not

no
