### ISSUE TITLE
[BUG] on hover element get invisible

### ISSUE THREAD

**Issue by Sawan-Kushwah** [ankit071105/Ticket-Booking#262]
### Description

![image](https://github.com/user-attachments/assets/e036a555-6707-47cd-b658-283abb27bd02)
on hovering it get invisible 
![image](https://github.com/user-attachments/assets/9cb4fe97-e418-4fea-831c-b06bf9e7442c)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/ankit071105/Ticket-Booking/blob/main/README.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by netranshi-tripathi** [comment]
i would like to work on it
