### ISSUE TITLE
Add a responsive password strength meter during sign-up.

### ISSUE THREAD

**Issue by PavanTeja2005** [ankit071105/Ticket-Booking#267]
I want to add a responsive password strength level meter which can display user's password strength when they are signing up.

It does.,
Display password strength to users as they create their passwords.
Improve user privacy by encouraging stronger passwords.
Enhance user experience with real-time feedback.

I'm working in gssoc extended. Please provide me suitable labels.

**Comment by ankit071105** [comment]
already assigned
