### ISSUE TITLE
[BUG] "File Not Found" Error for register.html

### ISSUE THREAD

**Issue by Lonewolf124** [ankit071105/Ticket-Booking#271]
### Description

When attempting to click on the Signup link in the navigation bar, the application throws a "File Not Found" error for /client/register.html. The file exists in the repository under the client folder, but it is not being located when accessed through the browser.

### Screenshots

![Screenshot 2024-10-09 073547](https://github.com/user-attachments/assets/7cedd773-b60f-43c7-9a3b-c103c51a6cc2)

### Any additional information?

**Steps to Reproduce:**

Navigate to the homepage (index.html).
Click on the Signup button in the navigation.
Observe the "File Not Found" error page.
Expected Behavior: Clicking the Signup button should load the register.html file located in the client folder, displaying the user registration page.

**Actual Behavior:** A "File Not Found" error is displayed, despite the register.html file existing in the correct folder.

**Causes:**
Incorrect File Path – The current path for register.html is set as /client/register.html, which may cause issues depending on the server setup. A relative path could resolve this.

**Suggested Fixes:**
Change the link in the navigation to a relative path: client/register.html.

### What browser are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/ankit071105/Ticket-Booking/blob/main/README.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by ankit071105** [comment]
Issue resolved the team was working on it
