### ISSUE TITLE
[BUG]Backend error in login /signup process

### ISSUE THREAD

**Issue by riyaaryan2004** [ankit071105/Ticket-Booking#275]
### Description

signin and login request is not going out.
No request in network section

### Screenshots

![Screenshot 2024-10-09 134646](https://github.com/user-attachments/assets/115dc19f-002d-405f-8c57-7401465972d7)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/ankit071105/Ticket-Booking/blob/main/README.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by riyaaryan2004** [comment]
@ankit071105 make sure u have set env variables on versel dashboard.
users still getting error in deployed link.

**Comment by ankit071105** [comment]
> @ankit071105 make sure u have set env variables on vercel dashboard. users still getting error in deployed link.

I havent not created env file you can create through the email which i have given you
