### ISSUE TITLE
Updating The Footer

### ISSUE THREAD

**Issue by Mandy1200** [ankit071105/Ticket-Booking#28]
Adding/Re-designing required elements in the footer

**Comment by Tanish0023** [comment]
Footer is not correctly attached to the bottom I can make this correct and add new details for the users. That will increaser user experience

**Comment by ankit071105** [comment]
> Footer is not correctly attached to the bottom I can make this correct and add new details for the users. That will increaser user experience

already assign buddy you can choose other issue
