### ISSUE TITLE
Adding Contact Form

### ISSUE THREAD

**Issue by Bhum-ika** [ankit071105/Ticket-Booking#286]
The Contact Us Section has the relevant info but it lacks the form. I can add that which will make it easy foruser to send feedback or any message directly through your website

Kindly assign this issue to me under hactoberfest, gssoc-ext and relevant tags.

**Comment by AshishCh01** [comment]
Hey @ankit071105 your website is missing contact us form which is very necessary for responsive website. Assign me this issue I will add the contact us form.

**Comment by ishivansmishra** [comment]
@ankit071105 kindly assign me this issue i can fix this issue
