### ISSUE TITLE
[BUG] slider section is covered by navbar

### ISSUE THREAD

**Issue by riyaaryan2004** [ankit071105/Ticket-Booking#289]
### Issue

1.Slider should be expected below nav bar.
2. Left button for slider is hidden

### Screenshot

![Screenshot 2024-10-10 175726](https://github.com/user-attachments/assets/d65c4cec-4d3f-417b-b642-8f9e7c3329c2)

![image](https://github.com/user-attachments/assets/8a46ebcf-9df4-4a72-97a2-34a075fd1c95)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/ankit071105/Ticket-Booking/blob/main/README.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by samriddhi122** [comment]
@ankit071105  please assign this issue to me .

**Comment by samriddhi122** [comment]
@ankit071105 please assign this issue to me under gssoc-ext and hacktoberfest

**Comment by Bishal-35** [comment]
I would like to work on it under GSSoC'24 and Hacktoberfest 2024 @ankit071105
