### ISSUE TITLE
Updating the About Us page

### ISSUE THREAD

**Issue by shreya20v** [ankit071105/Ticket-Booking#303]
### Description

The About Us page is very basic. We can beautify it by adding color, fonts, and images. By doing this it will become more attractive towards the user. I want to work on this issue.
@ankit071105  please assign this issue to me under the appropriate labels.
![image](https://github.com/user-attachments/assets/99365a46-925b-421c-a909-8e976d2998e2)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/ankit071105/Ticket-Booking/blob/main/README.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by Drupitha-Chandrashekar** [comment]
Even I would like to work on this issue. Can you please assign this issue to me with gssoc-ext and hacktoberfest-accepted labels? Also with appropriate level.

**Comment by Nihar4569** [comment]
please assign this issue to me
