### ISSUE TITLE
Duplicate "Ticket Marketplace" Text Appearing in the Header Section

### ISSUE THREAD

**Issue by VanshChitransh** [ankit071105/Ticket-Booking#313]
### Description

Description:

In the header section of the "Ticket Marketplace" project, the text "Ticket Marketplace" is displayed twice—once as part of the logo on the left side and again as plain text in the center-right. This redundancy leads to a cluttered UI and a confusing user experience.

I attempted to modify the header component by removing one of the instances, but this didn't resolve the issue, as both the logo and the text seem to come from different sources in the code. Further debugging is required to determine the root cause and remove the duplicate display effectively.

### Screenshots

![Screenshot from 2024-10-11 23-27-32](https://github.com/user-attachments/assets/20445a30-9d81-400d-8327-7d514845f367)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/ankit071105/Ticket-Booking/blob/main/README.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by Nihar4569** [comment]
I would like to work on this issue. Can you please assign this issue to me?
