### ISSUE TITLE
Added Scroll Progress Bar

### ISSUE THREAD

**Issue by sahilwadaskar07** [ankit071105/Ticket-Booking#314]
This PR introduces a scroll progress bar feature to visually represent how far the user has scrolled through a page. The bar fills as the user scrolls down the page and decreases as they scroll back up, providing a more intuitive navigation experience.

Changes Made:
1.Added a scroll progress bar that appears at the top of the page.
2.The progress bar width dynamically adjusts based on the user's scroll position.
3.The progress bar is styled using CSS for smooth transitions.
4.JavaScript is used to calculate the scroll position and update the width of the progress bar.

**Comment by ishivansmishra** [comment]
I will work under this project please assign me the project
