### ISSUE TITLE
[BUG] The cards are not aligned 

### ISSUE THREAD

**Issue by Mandy1200** [ankit071105/Ticket-Booking#319]
### Description

the cards on the body are equally aligned 

### Screenshots

![Screenshot (114)](https://github.com/user-attachments/assets/6799a8a7-a325-4a34-b511-d7818afaa9b2)

### Any additional information?

I will equally align and distrubute the cards

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/ankit071105/Ticket-Booking/blob/main/README.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by shantanumangalkar** [comment]
I’m interested in fixing this bug. Could you assign this issue to me?

**Comment by saimohan11** [comment]
assign me this task
