### ISSUE TITLE
Using reputed mail services for signup's.

### ISSUE THREAD

**Issue by smog-root** [ankit071105/Ticket-Booking#321]
Update the existing signup flow to validate email domains. Restrict signups to users with email addresses from trusted providers (e.g., Gmail, Outlook). etc.

Extract the domain from the user's email during signup. Compare it against a predefined list of trusted providers. If the domain matches, proceed with the signup; otherwise, return an error.

i'm expecting a gssoc-ext with level3 and a hacktoberfest-accepted label!

@ankit071105

**Comment by ankit071105** [comment]
Not required
