### ISSUE TITLE
Issue: Improve Visibility of Footer Section

### ISSUE THREAD

**Issue by ishita-1305** [ankit071105/Ticket-Booking#323]
Description:
The current footer layout has visibility issues due to overlapping elements and insufficient contrast between text and background.
![Screenshot 2024-10-12 210952](https://github.com/user-attachments/assets/539b4ea5-15bb-4031-a395-7909af95041c)

**Comment by Anirban780** [comment]
@ankit071105 could you also assign me to address the same issue ?
