### ISSUE TITLE
[BUG] PASSWORD STRENGTH METER

### ISSUE THREAD

**Issue by sindhuja184** [ankit071105/Ticket-Booking#330]
### Description

In the sign-up page I would like to add a progress-bar which would indicate the strength of the password.

This would enhance the User Interface.

Hope you assign the issue.

Thanks @ankit071105 

### Screenshots

![image](https://github.com/user-attachments/assets/d15391c5-f25d-47f3-9177-70c85d50facd)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/ankit071105/Ticket-Booking/blob/main/README.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by SATYAM0LUFFY** [comment]
@ankit071105  please assign this issue to me

**Comment by ankit071105** [comment]
Not required
