### ISSUE TITLE
[BUG]Sell Ticket section not available and improving Home page UI 

### ISSUE THREAD

**Issue by 30Abhi** [ankit071105/Ticket-Booking#343]
### Description

A sell ticket section taking ticket information taking about ticket number , travel destionation etc.
Managing home profile photos they are getting out of context 

### Screenshots

![image](https://github.com/user-attachments/assets/f5cf1df1-c729-490d-9a8e-fdefd53dc4e4)
![image](https://github.com/user-attachments/assets/32eba11c-a15e-436e-9dc4-52814f2134fd)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/ankit071105/Ticket-Booking/blob/main/README.md)
- [X] I'm a GSSoC'24-Extd contributor
- [ ] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by ankit071105** [comment]
already assigned
