### ISSUE TITLE
want to improve hero section by adjusting image height and text allignment

### ISSUE THREAD

**Issue by rahulbamnuya** [ankit071105/Ticket-Booking#344]
![Uploading Screenshot (168).png…]()

**Comment by YasirKhan231** [comment]
Image are not showing properly so it create an bad effect on the website 
![image](https://github.com/user-attachments/assets/a20101b3-d1dc-4216-9087-eee647dda9ab)

@ankit071105 assign this task to me

**Comment by ankit071105** [comment]
it is fixed
