### ISSUE TITLE
Font size

### ISSUE THREAD

**Issue by Kajalmehta29** [ankit071105/Ticket-Booking#346]
<img width="1220" alt="Screenshot 2024-10-13 at 7 32 49 PM" src="https://github.com/user-attachments/assets/2cc3f4d3-e8dc-442a-9a2c-2535b9bdbbcd">

The size of heading is smaller than the content which is looking a bit odd. I want to work on this issue.
Please assign this issue to me under gssoc-extd and hacktoberfest.

**Comment by ankit071105** [comment]
Not required
