### ISSUE TITLE
Want to make dark mode better!!

### ISSUE THREAD

**Issue by DrashtiMistry** [ankit071105/Ticket-Booking#350]
![Uploading Screenshot 2024-10-13 211050.png…]()
![Screenshot 2024-10-13 211103](https://github.com/user-attachments/assets/0ef86585-0b77-42a0-95cc-ac653f7fb17a)

Hii @sanjay-kv .. 
Please assign this issue to me. I want to make the dark mode of this website better by changing some css.

**Comment by ankit071105** [comment]
Not required
