### ISSUE TITLE
Want to make sign Up page better

### ISSUE THREAD

**Issue by DrashtiMistry** [ankit071105/Ticket-Booking#351]
![Screenshot 2024-10-13 211138](https://github.com/user-attachments/assets/2520c345-3e37-45a5-80b4-14f8340a48bb)

Hello @sanjay-kv 
I want to make the sign Up page better please assign this issue to me.

**Comment by ankit071105** [comment]
So some design through images or screen recording , what you acutal want to changes in the website .

**Comment by DrashtiMistry** [comment]
I want to make this sign up Better as it looks like doesn't match to website. So I want to make like it matches to the website
