### ISSUE TITLE
[BUG] Contact button not working

### ISSUE THREAD

**Issue by Ujjwal5705** [ankit071105/Ticket-Booking#353]
### Description

As we click on Contact button nothing appears, Their is either a bug in the Contact button or need to design another Contact page.

### Video of the bug

https://github.com/user-attachments/assets/e0644853-743d-4a3e-b0c9-0145d2d68026

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/ankit071105/Ticket-Booking/blob/main/README.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by ankit071105** [comment]
Not required our team will handle this small issue
