### ISSUE TITLE
Footer and navbar for about us page.

### ISSUE THREAD

**Issue by pranavsuriya-sr** [ankit071105/Ticket-Booking#354]
### Description

Add the footer and navbar for the about us page. 

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/ankit071105/Ticket-Booking/blob/main/README.md)
- [ ] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by pranavsuriya-sr** [comment]
Please assign this issue to me.

**Comment by ankit071105** [comment]
Not required
