### ISSUE TITLE
[Feature Enhancement] Signin/Signup Page theme doesn't match the UI of website

### ISSUE THREAD

**Issue by Ujjwal5705** [ankit071105/Ticket-Booking#355]
### Description

I would like to improve the UI of SIgnin/Signup page. As of now its very simple and plain, not aligning with the theme of website.

### Website theme:

![Screenshot 2024-10-13 232303](https://github.com/user-attachments/assets/bb38f62f-177a-458d-80aa-55e63712c942)

### SIgnin/Signup page:

![Screenshot 2024-10-13 222521](https://github.com/user-attachments/assets/254fc9a5-6c8b-43df-bd97-731e58e7a57f)

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/ankit071105/Ticket-Booking/blob/main/README.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by ankit071105** [comment]
What changes you want to do mention them with images or video . so that if ui will be good then we will assign you

**Comment by Ujjwal5705** [comment]
@ankit071105 I can't provide the exact image or video right now but i can propose some changes.
I will replace the orange “Log in” and “Register” buttons with the teal/green used in the main site for consistency.
Instead of white background a darker shade (similar to the header) or a image with low opacity related to the website. The "Book Bus or Train Tickets" heading from the main site has a clean, sans-serif font while "Welcome!" and "Sign up" are of different typography. The whitespace between the “Welcome!” section and the form should be reduced as the main website uses a tighter, more compact design. More prominent border and shadow should be used in Signup form.
