### ISSUE TITLE
[BUG] Contact button on navbar is not redirecting to contact page.

### ISSUE THREAD

**Issue by varma-101** [ankit071105/Ticket-Booking#359]
### Screenshots

![Uploading image.png…]()

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/ankit071105/Ticket-Booking/blob/main/README.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by pranavmugatkar** [comment]
hey @varma-101, can you assign me for this issue under hactoberfest label
