### ISSUE TITLE
 Fix Image Aspect Ratio Issues

### ISSUE THREAD

**Issue by shreyad2806** [ankit071105/Ticket-Booking#36]
Image are not proper and are overlapping.
![WhatsApp Image 2024-10-02 at 14 13 58_0ad35abb](https://github.com/user-attachments/assets/f42ca8d3-e136-451e-bb77-fee128b10285)

**Comment by ankit071105** [comment]
First show me a solution in image of ss or record a video what solution does you want to give to this 
Make a star to repos 
follow my github profile  
fork into the repos

**Comment by shreyad2806** [comment]
In these photos ticket booking and the other text are hiding. I will resize the image and margin and make it proper.
![Screenshot 2024-10-02 141229](https://github.com/user-attachments/assets/ba108f46-feb8-4955-b9ca-7132f4c0af83)

![Screenshot 2024-10-02 141118](https://github.com/user-attachments/assets/a33e0606-864b-4349-839b-0e3e70cd1665)

**Comment by ankit071105** [comment]
> In these photos ticket booking and the other text are hiding. I will resize the image and margin and make it proper. ![Screenshot 2024-10-02 141229](https://private-user-images.githubusercontent.com/167011296/372822476-ba108f46-feb8-4955-b9ca-7132f4c0af83.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4NjM5MTUsIm5iZiI6MTcyNzg2MzYxNSwicGF0aCI6Ii8xNjcwMTEyOTYvMzcyODIyNDc2LWJhMTA4ZjQ2LWZlYjgtNDk1NS1iOWNhLTcxMzJmNGMwYWY4My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwMlQxMDA2NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMjY1YjljMWQxNGEyZDNmMWNjZWQ4NDc5ODllNzA2ZmMzZDQ4MTg4NDI1ZjMwNDg5Y2ZhYjA3M2I4ZmUwNDk0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Dke3066GdEPRH326UZaDlgwW_O3qaXWU6d5dfqwF9Dw)
> 
> ![Screenshot 2024-10-02 141118](https://private-user-images.githubusercontent.com/167011296/372822501-a33e0606-864b-4349-839b-0e3e70cd1665.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4NjM5MTUsIm5iZiI6MTcyNzg2MzYxNSwicGF0aCI6Ii8xNjcwMTEyOTYvMzcyODIyNTAxLWEzM2UwNjA2LTg2NGItNDM0OS04MzliLTBlM2U3MGNkMTY2NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwMlQxMDA2NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYjIwZGQ0ODkzNDljZmE2MjM4ZjFmNDkyMTIzOGUwYzA1M2JkN2VmN2U4MWQ0YjM5MGFmNmExNzE2MGNlYzRkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.qQQQX6ZBLChJ8ZWU217fWtp4dxqnWElBa62IMRCq4Ts)

Okay resize but show me the solution then i can assign that issue
