### ISSUE TITLE
need little improvement for our reviews section.

### ISSUE THREAD

**Issue by Yashwanthreddy1789** [ankit071105/Ticket-Booking#364]
Transitions are need to be added for 'our reviews' sections to looks interactive .

**Comment by anudsilva** [comment]
hey @ankit071105 I would like to work on this issue (issue #364), I'll make the changes and send a screenshot/ screen-recording

**Comment by anudsilva** [comment]
https://github.com/user-attachments/assets/fb92b92a-b9a6-469d-a27a-096f7e7bb49e

@ankit071105 Please review this and let me know
