### ISSUE TITLE
[BUG] :Want to improve footer section

### ISSUE THREAD

**Issue by sanikamandale17** [ankit071105/Ticket-Booking#378]
### Description

Want to improve footer section adding some hover effects into all icons including socail media icons...also make it more interactive
Plz assign this issue to me @ankit071105  i want to work on it

### Screenshots

![image](https://github.com/user-attachments/assets/f4a05609-a7ee-4cd9-b152-74deeab47610)

### Any additional information?

n/a

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/ankit071105/Ticket-Booking/blob/main/README.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by harshita2303** [comment]
please assign this issue to me i want to work on this @ankit071105
