### ISSUE TITLE
Integrate External APIs for Trip Data

### ISSUE THREAD

**Issue by ykchoudhary110** [ankit071105/Ticket-Booking#398]
Description: Integrate third-party APIs that provide additional trip data, including popular routes, seasonal trends, and pricing information.

Task:
Identify suitable APIs for bus and train schedules, route popularity, and pricing.
Implement the API calls and display the data on the ticket browsing pages.

Label: enhancement, API, frontend

Priority: Medium

**Comment by ankit071105** [comment]
No our website  provides us if user want to sell his ticket then he can list that out and if any user will buy that some reduce amount will get by seller and some high amount have to pay by user who's buy

**Comment by ykchoudhary110** [comment]
But its illegal in india to sell or transfer tickets  other than any blood
relatives
