### ISSUE TITLE
Dark/Light Mode Toggle Button in Navbar Not Changing.

### ISSUE THREAD

**Issue by surajgoraicse** [ankit071105/Ticket-Booking#4]
***Description:***
Dark/Light Mode Toggle Button Icon Does Not Change  in the Navbar.
**Possible Solution:**  
- Implement a conditional rendering of the icon based on the current theme (e.g., showing a sun icon for light mode and a moon icon for dark mode).
- Ensure that the icon updates dynamically when the mode is toggled.
Please assign me this task.

***Dark Mode***

![1](https://github.com/user-attachments/assets/97de8372-ea6a-4fb3-946a-eefca3a843ab)

***Light Mode***

![2](https://github.com/user-attachments/assets/73af82b4-f7e7-4558-bf24-6583b7a5005a)

**Comment by Satyam30raj** [comment]
Please Assign me the task.. I have pretty much good knowledge about these kinds of issues.

**Comment by ankit071105** [comment]
> Please Assign me the task.. I have pretty much good knowledge about these kinds of issues.

already first i have to see his code then yours
