### ISSUE TITLE
Slider Photos are not in scope

### ISSUE THREAD

**Issue by Saloni3494** [ankit071105/Ticket-Booking#41]
![image](https://github.com/user-attachments/assets/e77eaad8-d91c-424a-910b-fb9ce50bdb90)

The first look of site are the slider photos that appear, since they are not in scope and goes out of box it seems to be irrelevant.

**Comment by ankit071105** [comment]
Okay provide me a solution in image form . 
Follow github id
make a star to the repos @Saloni3494

**Comment by ankit071105** [comment]
> ![image](https://private-user-images.githubusercontent.com/138001726/372918981-d01a9470-caf3-43f7-b24b-87c486e0838f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4ODMwODUsIm5iZiI6MTcyNzg4Mjc4NSwicGF0aCI6Ii8xMzgwMDE3MjYvMzcyOTE4OTgxLWQwMWE5NDcwLWNhZjMtNDNmNy1iMjRiLTg3YzQ4NmUwODM4Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwMlQxNTI2MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YmYxNDYyMDBjZGZhOWZmMjNiYzEzNDQxNzNjYjk0NzBjNjMxNDM3MjcxMWU0ZTBjYjRlZDNmOTU2MDA3YjUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.yhoUP1AXWmHdvsVyjM4TGbK5Aj92MSBRgTsLeVtirkk)
> 
> This image along with other images can be filled in a visible manner, at present it is not fully visible which makes the site less impressive.

you want to perform this issue ?

**Comment by Saloni3494** [comment]
yes

**Comment by ankit071105** [comment]
> yes

okay i am assiging this issue to you
