### ISSUE TITLE
Navbar Overlapping Sliding Images Section

### ISSUE THREAD

**Issue by Subham1** [ankit071105/Ticket-Booking#415]
### Description

The navbar overlapping the sliding images section causes visual obstruction, making key content (like images) partially hidden. This disturbs the page’s layout and reduces its overall aesthetic appeal. Users may find it difficult to interact with navigation elements, leading to frustration. The design looks unbalanced and less professional, negatively impacting the user experience.

### Screenshots

![image](https://github.com/user-attachments/assets/92d46492-a515-47b3-b05a-b302cf8cafc5)

![image](https://github.com/user-attachments/assets/32a324ab-bc87-40bb-b017-c64d1a2aad02)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/ankit071105/Ticket-Booking/blob/main/README.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by sanjay-kv** [comment]
@Subham1 im not project admin i cant assign the project to you, tag mentor or PA
