### ISSUE TITLE
[BUG] ABOUT US SECTION IS NOT RESPONSIVE

### ISSUE THREAD

**Issue by shriyadindi** [ankit071105/Ticket-Booking#417]
### Description

I would like to work on the About us section to make it responsive 

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/ankit071105/Ticket-Booking/blob/main/README.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by ankit071105** [comment]
okay i am assiging this
