### ISSUE TITLE
Enhancement of the book your ticket section user interface.

### ISSUE THREAD

**Issue by shriyadindi** [ankit071105/Ticket-Booking#418]
I would like to enhance the user interface of the book your ticket section.
![Screenshot 2024-10-17 234359](https://github.com/user-attachments/assets/8ab1dd7a-0d8a-4b94-88d1-1af93c5da19a)

**Comment by ankit071105** [comment]
show som esolution

**Comment by shriyadindi** [comment]
Kindly asssign me this issue, i would like to work on it.
