### ISSUE TITLE
About Us section is short and imprecise

### ISSUE THREAD

**Issue by Saloni3494** [ankit071105/Ticket-Booking#42]
![image](https://github.com/user-attachments/assets/f0bde99c-9cd4-4244-87a3-eb8b9eb284bf)

About Us section should be effective filled with images to attract customers.

**Comment by ankit071105** [comment]
> ![image](https://private-user-images.githubusercontent.com/138001726/372860935-f0bde99c-9cd4-4244-87a3-eb8b9eb284bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4NzQ3ODYsIm5iZiI6MTcyNzg3NDQ4NiwicGF0aCI6Ii8xMzgwMDE3MjYvMzcyODYwOTM1LWYwYmRlOTljLTljZDQtNDI0NC04N2EzLWViOGI5ZWIyODRiZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwMlQxMzA4MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZmE1ZGEwNTI5Mjk3YTIxOGExN2RkMTJiMmE0MGE1MWUxZjk3MTY0MTNlNTFlNzRhNGM4MmUzZTNjYmU0MzFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Ppt37jBjFORO-bXnnjdYmu0pX0I1EhkxmlRyY7bc3uc)
> 
> About Us section should be effective filled with images to attract customers.

Okay provide me a solution in image form . 
Follow github id
make a star to the repos

**Comment by ankit071105** [comment]
> I can make the About Us section like this. Assign me for that. ![About us](https://private-user-images.githubusercontent.com/135465642/372891390-76e8a7dd-9920-4ad6-900e-7c1468aa78bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4NzgxMzksIm5iZiI6MTcyNzg3NzgzOSwicGF0aCI6Ii8xMzU0NjU2NDIvMzcyODkxMzkwLTc2ZThhN2RkLTk5MjAtNGFkNi05MDBlLTdjMTQ2OGFhNzhiZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwMlQxNDAzNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZWQ5ZjAxNWI1NWQ2NjUzMDZlYWQ4YjMzNTQzZGQ4N2IwNGQ5ZDYyMTg4ZjA5OTlhM2ZmNTgxYTA0NjUxMDA3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.UFj6rdVg8xHHTRRI9zkyenEda05xs4FpZUHjR5FJ444)

okay make it complete responsive too @sahilwadaskar07
