### ISSUE TITLE
[BUG] UI and Functionality Improvements Needed

### ISSUE THREAD

**Issue by srishti023** [ankit071105/Ticket-Booking#423]
### Description

Hamburger Menu: The hamburger menu is not functioning properly, making navigation difficult.

Contribution Page: The contribution page is not responsive on mobile devices, leading to a poor user experience.

Navbar Visibility: A navbar is needed on every page except the login and signup pages to improve navigation consistency.

### Screenshots

Hamburger is not working :

https://github.com/user-attachments/assets/b81680d1-2030-4697-b8d0-c087b4fcefab

Contribution page is not responsive : 

Uploading Contributors - Google Chrome 2024-10-18 12-18-22.mp4…

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/ankit071105/Ticket-Booking/blob/main/README.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by Osank31** [comment]
can you assign me this issue?

**Comment by srishti023** [comment]
hey @ankit071105  can you please give me level 2 or 3 badge!
