### ISSUE TITLE
[BUG] No back or home button on ABOUT US PAGE

### ISSUE THREAD

**Issue by anishka25** [ankit071105/Ticket-Booking#425]
### Description

I need to add a button and functionality to go back to the home page after landing on the about us page to improve the UX of this website.

### Screenshots

![image](https://github.com/user-attachments/assets/ce60c6e3-e1b7-483d-94eb-3c855bffb171)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/ankit071105/Ticket-Booking/blob/main/README.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by Samuel-0316** [comment]
@anishka25 I have raised a pull request fixing this bug
plzz check it out and encourage them to merge the pull request

**Comment by anishka25** [comment]
Excuse me @Samuel-0316 , this is my issue that i have created , i guess you should read the guidelines on how to participate in gssoc. I was waiting for the author to assign this issue to me.

**Comment by Samuel-0316** [comment]
ok sorry @anishka25

**Comment by ankit071105** [comment]
> Excuse me @Samuel-0316 , this is my issue that i have created , i guess you should read the guidelines on how to participate in gssoc. I was waiting for the author to assign this issue to me.
> 
> @ankit071105 please look into this !

okay dont fight among yourself i am assignig this to you @anishka25  You can generate a PR Happy Coding !!!!!
