### ISSUE TITLE
Map seems to be much wider

### ISSUE THREAD

**Issue by Saloni3494** [ankit071105/Ticket-Booking#43]
![image](https://github.com/user-attachments/assets/106886a2-2440-4c4e-b7cf-8d9904ea6dc3)

Observing the google maps of various standard sites it seems that the map in your site is much wider which gives non-professional look.

**Comment by ankit071105** [comment]
> ![image](https://private-user-images.githubusercontent.com/138001726/372861893-106886a2-2440-4c4e-b7cf-8d9904ea6dc3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4NzQ2NjgsIm5iZiI6MTcyNzg3NDM2OCwicGF0aCI6Ii8xMzgwMDE3MjYvMzcyODYxODkzLTEwNjg4NmEyLTI0NDAtNGM0ZS1iN2NmLThkOTkwNGVhNmRjMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwMlQxMzA2MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZTM3ZjYxYTZkZGNlNjliNDY5MzNlYjEyODU1YzljMGZjZmE3NTRmNmRmZTUwMzllOWYxNzBkNTZlOGQwNjVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.yz5p9zQX7Yp1atiV_JhDP3mwGdqdURWtj4JPlFwa9LE)
> 
> Observing the google maps of various standard sites it seems that the map in your site is much wider which gives non-professional look.

If you have any solution provide me in form of video or images then i will assign to you

**Comment by Saloni3494** [comment]
![map](https://github.com/user-attachments/assets/25917483-d085-4973-9713-dbb3732fa89e)

I change map as shown in image, assign the issue to me

**Comment by ankit071105** [comment]
> ![map](https://private-user-images.githubusercontent.com/138001726/372920981-25917483-d085-4973-9713-dbb3732fa89e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4ODMwMjYsIm5iZiI6MTcyNzg4MjcyNiwicGF0aCI6Ii8xMzgwMDE3MjYvMzcyOTIwOTgxLTI1OTE3NDgzLWQwODUtNDk3My05NzEzLWRiYjM3MzJmYTg5ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwMlQxNTI1MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ODY5ZDQwMjY3ODRlMmIxNTRkNTYzYzQ0YTZmMDc3YzZkZjBmZGI0YTJmMDUwNWFjY2FmYzdhOGY4Y2QxY2NkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.w7etatQJ541YIy-XFRtaUlIXZ1kPQT_KDzuJep-O_gE)
> 
> I change map as shown in image, assign the issue to me

go for it assigned to @Saloni3494

**Comment by SumitSahu44** [comment]
hey, @ankit071105  I'm prety sure that i will solve this and build it with new design so assign this to me under the gssoc-ext label and level2 label so i will help me also

**Comment by ankit071105** [comment]
> hey, @ankit071105 I'm prety sure that i will solve this and build it with new design so assign this to me under the gssoc-ext label and level2 label so i will help me also

bro already assign generate new issue or contribute to another one

**Comment by SumitSahu44** [comment]
@ankit071105 can you assign me i will do within 1hr so please assign me with label gssoc-ext

**Comment by ankit071105** [comment]
> @ankit071105 can you assign me i will do within 1hr so please assign me with label gssoc-ext

okay i am assiging you this issue @SumitSahu44

**Comment by SumitSahu44** [comment]
i pull the code and solve conflict check it and please add all labels gssoc-ext, level2 and hacktoberfest-accepted

**Comment by SumitSahu44** [comment]
@ankit071105 sorry to again but my side not see any label so please add once again level 2label i copleted this repo and you merge it already

**Comment by SumitSahu44** [comment]
@ankit071105 closed it i done it #149 pull request and add label if not added
