### ISSUE TITLE
[BUG] The Submit Button is not clearly visible.

### ISSUE THREAD

**Issue by Sudhanshu248** [ankit071105/Ticket-Booking#431]
### Description

In the feedback form submit form is not clearly visible.

### Screenshots

![Screenshot 2024-10-18 171558](https://github.com/user-attachments/assets/cc912323-33bf-40bb-8ebd-1b8a6dd41608)

### Any additional information?

As the button is not clearly visible, user will face the problem.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/ankit071105/Ticket-Booking/blob/main/README.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by ishivansmishra** [comment]
@ankit071105 Kindly please assign me this issue under the label of gssoc-ext, hacktoberfest'24, hacktoberfest-accepted and appropriate level

**Comment by Nayanbatman** [comment]
@ankit071105 Kindly please assign me this issue under the label of gssoc-ext, hacktoberfest'24, hacktoberfest-accepted and appropriate level

**Comment by Sudhanshu248** [comment]
@ankit071105 Sir, Please add the label of gssoc'24, gssoc-ext, hacktoberfest'24,  hacktoberfest-accepted,  appropriate level.
