### ISSUE TITLE
[BUG] Improve FAQ section

### ISSUE THREAD

**Issue by Himanshu-kumar025** [ankit071105/Ticket-Booking#437]
### Description

I wanna to improve UI of the FAQ section according to the website theme . I like to work on this under GSSOC'24 Hacktofest'24
thank you

### Screenshots

![faq2024](https://github.com/user-attachments/assets/fe2896ef-6096-4399-958e-a8207cf55222)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/ankit071105/Ticket-Booking/blob/main/README.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by ankit071105** [comment]
It has been solved last night you can check now
