### ISSUE TITLE
[BUG] Add Navigation Bar to Contributors Page for Improved Navigation

### ISSUE THREAD

**Issue by AnshikaaaBansal** [ankit071105/Ticket-Booking#439]
### Description

The current "Our Contributors" page lacks a navigation bar, making it difficult for users to return to the home page or navigate to other sections of the website. This omission affects user experience, as there is no direct way to access the main menu or switch to other pages. Adding a navigation bar to this page will enable seamless navigation throughout the site.

Refer to the attached screenshot showing the "Our Contributors" page without the navigation bar for a visual reference.

![Screenshot 2024-10-18 223704](https://github.com/user-attachments/assets/a07cad5d-8a56-4523-bbbc-33316829be78)

### Screenshots

Go to the "Our Contributors" page.
Notice the absence of the navigation bar at the top of the page.
Try finding a way to return to the home page without manually typing the URL or using the browser's back button.

### Any additional information?

Adding the navigation bar will align the "Our Contributors" page with the rest of the site's design, ensuring consistent navigation options across all pages.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/ankit071105/Ticket-Booking/blob/main/README.md)
- [X] I'm a GSSoC'24-Extd contributor
- [ ] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by ankit071105** [comment]
already resolved
