### ISSUE TITLE
[BUG] add hover effect in project static section

### ISSUE THREAD

**Issue by Himanshu-kumar025** [ankit071105/Ticket-Booking#441]
### Description

I saw there is no hover effect on the project static section .I would like to work on this issue under GSSOC'24 and Hacktofest'24
thank you

### Screenshots

![project static](https://github.com/user-attachments/assets/04f9da80-7082-41b7-8798-61928b7d3c80)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/ankit071105/Ticket-Booking/blob/main/README.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by ankit071105** [comment]
Dont raise same issue in two forms
