### ISSUE TITLE
[BUG] Improve the UI of contributors front page 

### ISSUE THREAD

**Issue by Himanshu-kumar025** [ankit071105/Ticket-Booking#442]
### Description

I would like to improve the UI of the Contributor front page  under GSSOC'24 and Hacktofest'24 
thank you

### Screenshots

![contributer page](https://github.com/user-attachments/assets/988d76b5-232f-41f1-a07a-7e8889aace19)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/ankit071105/Ticket-Booking/blob/main/README.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by anchalchaturvedi08** [comment]
I want to work on this issue, can you assign me this task?

**Comment by Himanshu-kumar025** [comment]
@ankit071105 please assign me on this issue officially  .
