### ISSUE TITLE
[BUG] Misalignment of Moon Icon in Navbar

### ISSUE THREAD

**Issue by Nayanbatman** [ankit071105/Ticket-Booking#446]
### Description

The moon icon in the of the repository's UI is nit aligned , which affects the overall visual harmony and consistency of the design . The misalignment could be attribute to CSS positioning , alignment settings , or an issue with the icon's implementation.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/ankit071105/Ticket-Booking/blob/main/README.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by Nayanbatman** [comment]
please sir assign me this issue . I can fix it .

**Comment by ankit071105** [comment]
It has been solved now
