### ISSUE TITLE
[BUG] two login pages appearing and improbving ui/ux of login and register page.

### ISSUE THREAD

**Issue by vidhi-github** [ankit071105/Ticket-Booking#447]
### Description

2login pages are appearing when trying to sign in. also the login and register pages are ui/ux. I would like to add some ui/ux to those pages to make them look more presentable.

kindly assign me this issue under gssoc-ext and hacktoberfest accepted also under good level plz.

### Screenshots

![Screenshot (100)](https://github.com/user-attachments/assets/e7a45325-c379-43c8-b933-202df77d7814)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/ankit071105/Ticket-Booking/blob/main/README.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by ankit071105** [comment]
Resolved
