### ISSUE TITLE
[BUG] connect contact us ,, help us links present in footer to contact us page. Adding email to contact us page.

### ISSUE THREAD

**Issue by vidhi-github** [ankit071105/Ticket-Booking#448]
### Description

would like to connect contact us and help us links present in footer point to the contact us option.

Also a project without copyright symbol is always incomplete. i would also like to add copyright symbol in the footer of the website.

also,, adding an email textarea would e great in contact us option.

kindly assign me this issue under gssoc-ext and hacktoberfest accepted.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/ankit071105/Ticket-Booking/blob/main/README.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by ankit071105** [comment]
Show some ss or videos what acutally want to change
