### ISSUE TITLE
#make the website available in multiple languages thus by improving its accessibility.

### ISSUE THREAD

**Issue by SanikaBhalerao1345** [ankit071105/Ticket-Booking#46]
create a working dropdown with various languages spoken in different regions.

**Comment by ankit071105** [comment]
> create a working dropdown with various languages spoken in different regions.

okay work like that if user changes the languages then whole website languages get changed @SanikaBhalerao1345  if you have solution i will assign this to you

**Comment by SanikaBhalerao1345** [comment]
Hi @ankit071105 , yes I would like to work on this issue.

**Comment by ankit071105** [comment]
> Hi @ankit071105 , yes I would like to work on this issue.

okay i am assiging this to you

**Comment by SumitSahu44** [comment]
hey assign this to me i will make your website in different language under gssoc-ext label

**Comment by ankit071105** [comment]
> hey assign this to me i will make your website in different language under gssoc-ext label

The issue is when user changes the languages then whole website languages get changed . if can this i will assign this to you . @SumitSahu44

**Comment by SumitSahu44** [comment]
hey @ankit071105 I'm raady to do this in a single click we can change english to hindi language we have 2 options 
1- As per your current structure we can do this usinh HTML CSS and JS
2- Using reactjs so suggest me what tech stack i use to do this

**Comment by ankit071105** [comment]
> hey @ankit071105 I'm raady to do this in a single click we can change english to hindi language we have 2 options 1- As per your current structure we can do this usinh HTML CSS and JS 2- Using reactjs so suggest me what tech stack i use to do this

current one only

**Comment by SumitSahu44** [comment]
ok assign this to me i will build it and also add all labels

**Comment by SumitSahu44** [comment]
hey @ankit071105 assign this to me with all labels i will do it

**Comment by SanikaBhalerao1345** [comment]
hi @ankit071105 can i still raise PR?
