### ISSUE TITLE
[BUG] Enhance the design of contact us section

### ISSUE THREAD

**Issue by Sudhanshu248** [ankit071105/Ticket-Booking#472]
### Description

Currently the contact us section is not looks so good.

I would like to make more attractive with adding some design along with hover effect

### Screenshots

Currently:

![Screenshot 2024-10-19 233640](https://github.com/user-attachments/assets/5723d925-500b-420c-bd5f-3b86a2db42f5)

I would like to make it like this:

![Screenshot 2024-10-19 233742](https://github.com/user-attachments/assets/8cc039f3-c735-4c36-a8a7-9a1852a7bd00)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/ankit071105/Ticket-Booking/blob/main/README.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by Sudhanshu248** [comment]
@ankit071105 Please assign me this issue under the label of gssoc'24, hacktoberfest'24, hacktoberfest-accepted, level-3.

**Comment by ankit071105** [comment]
It will be similar code and it has been used in several webpages @Sudhanshu248  so show some unique approach
