### ISSUE TITLE
Can be Improved By Adding Destination and origin Interface

### ISSUE THREAD

**Issue by Sudhanshutiwari-cs** [ankit071105/Ticket-Booking#48]
Websites UI can be Improved By adding a origin and destination interface..it will help users to search according it..and it will look more professional.. Hence therefore assign me this

**Comment by ankit071105** [comment]
> Websites UI can be Improved By adding a origin and destination interface..it will help users to search according it..and it will look more professional.. Hence therefore assign me this

provide me a solution video of what all changes you are performing then i will assign it you @Sudhanshutiwari-cs

**Comment by Sudhanshutiwari-cs** [comment]
@sambedan1 Sure Working with All these to make website More Comfortable For users...and make it different from other Competition website in this field

**Comment by Sudhanshutiwari-cs** [comment]
@ankit071105 Will Be Providing Video Solution by Day after Tommorow with full workflow
