### ISSUE TITLE
UI of website

### ISSUE THREAD

**Issue by RitikaMaha** [ankit071105/Ticket-Booking#482]
Below is the attached UI of site. I think the icons on right side and in general background color doesn;t match with the website.
So I would like to manage changes with  background color and enhancement of icon size a little bit @sanjay-kv and @ankit071105 pl assign me the task

![image](https://github.com/user-attachments/assets/14ced692-8121-4b19-a963-e91ddab56064)

**Comment by Varshatm218** [comment]
Assign this to me under GSSoC-extd

**Comment by RitikaMaha** [comment]
@ankit071105 why did you add bug ?
