### ISSUE TITLE
[BUG] The social media icons on the footer do not work

### ISSUE THREAD

**Issue by avogadroB** [ankit071105/Ticket-Booking#493]
### Description

when you click on the icons in the footer, they do no redirect you to the required website. They just take you to the top of the page.

### Screenshots

![image](https://github.com/user-attachments/assets/93bc260d-21aa-4495-bad1-fd60111b2ef2)

### What browser are you seeing the problem on?

Firefox, Chrome

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/ankit071105/Ticket-Booking/blob/main/README.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by ishitab02** [comment]
hey, can you assign this issue to me?

**Comment by avogadroB** [comment]
Hey I am already working on this, just waiting for it to be assigned to me.
