### ISSUE TITLE
Add 'Follow Us on Social Media' Section

### ISSUE THREAD

**Issue by AswaniBolisetti** [ankit071105/Ticket-Booking#50]
Issue Description:
The website currently lacks a 'Follow Us on Social Media' section. I propose adding social media links (icons and handles) to encourage users to connect with us on platforms like Facebook, Twitter, Instagram, etc.

I’d like to work on adding this feature. Please assign this issue to me under gssoc-ext, GSSoC, hacktoberfest-accepted

**Comment by INam1995** [comment]
I would like to work on this feature. Please assign this issue to me under the labels gssoc-ext, GSSoC. I propose adding social media links (icons and handles) to encourage users to connect with us on platforms like Facebook, Twitter, Instagram, and more.

**Comment by SumitSahu44** [comment]
I would like to work on adding a "Follow Us on Social Media" section to the website. This feature will include social media icons and links (Facebook, Twitter, Instagram, etc.) to encourage users to connect with us on various platforms. Please assign this issue to me under labels: gssoc-ext,, hacktoberfest-accepted.
