### ISSUE TITLE
enhacing the ui of train sell html page

### ISSUE THREAD

**Issue by Prabhatsingh001** [ankit071105/Ticket-Booking#507]
![Screenshot 2024-10-21 183034](https://github.com/user-attachments/assets/ffbd4526-a41d-491a-b203-c0e77d632c11)
![Screenshot 2024-10-21 183051](https://github.com/user-attachments/assets/928c0f8e-b6b6-4ac1-83d7-d83e5c62c7c5)

and overall the UI of the page

**Comment by aahanajena** [comment]
assign me the issue. i will fix it
