### ISSUE TITLE
[BUG] : UI IMPROVEMENT IN "BOOK BUS OR TRAIN TICKETS" SECTION IN HOME

### ISSUE THREAD

**Issue by isimarjitsingh** [ankit071105/Ticket-Booking#509]
### Description

as i observe the UI (DESIGNING) of your "book bus or train tickets" section is very ordinary  please assign me this issue as  i able to provide:-
- eye catching colors
- hovering effects
- transitions
- smooth user interface
- relevant pictures

### Screenshots

CURRENT DESIGNING:-
![Screenshot 2024-10-21 204148](https://github.com/user-attachments/assets/28bdbdf1-3fde-4228-832e-64d2dee29bfd)

### Any additional information?

KINDLY ASSIGN ME THIS WORK UNDER GSSOC EXTD SO THAT I WILL LOOK FORWARD TO CONTRIBUTE

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/ankit071105/Ticket-Booking/blob/main/README.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by himasnhu018** [comment]
assign me please
