### ISSUE TITLE
Add move to top button and adding link to NavBrand logo and FAQ section

### ISSUE THREAD

**Issue by govindumeesala** [ankit071105/Ticket-Booking#51]
move to top button improves user exprience and allows to navigate to top of the page easily

Adding link to home page to the logo in navbar is a good practice 

Adding faq section improves websites user experience 

Assign it to me I would like to work on it

**Comment by SumitSahu44** [comment]
Hi, I'd love to contribute to the project by adding a 'move to top' button and linking the NavBrand logo to the homepage and the FAQ section. I have experience working with front-end web development and can implement these features efficiently. Looking forward to your guidance!

**Comment by SumitSahu44** [comment]
Thank's for merging my pull request, can you assign labels like gssoc-ext because i worked under the gssoc-ext

**Comment by SumitSahu44** [comment]
@ankit071105 please add labels
