### ISSUE TITLE
[BUG] UI IMPROVEMENT OF "FEEDBACK" SECTION IN HOME 

### ISSUE THREAD

**Issue by isimarjitsingh** [ankit071105/Ticket-Booking#513]
### Description

as i observe the UI (DESIGNING) of your "Frequently Asked Questions" section is very ordinary  please assign me this issue as  i able to provide:-
- eye catching colors
- hovering effects
- transitions
- smooth user interface
- relevant pictures

PLEASE ASSIGN ME THIS WORK UNDER GSSOC EXTD

### Screenshots

CURRENT DESIGNING:--
![Screenshot 2024-10-21 211113](https://github.com/user-attachments/assets/3985c62d-3632-471a-ab8d-9d00a81e02be)

### Any additional information?

PLEASE ASSIGN ME THIS WORK UNDER GSSOC EXTD SO THAT I WILL LOOK FORWAD TO CONTRIBUTE

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/ankit071105/Ticket-Booking/blob/main/README.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by arpit74170** [comment]
please Give this task to me i will fix it
