### ISSUE TITLE
I have found your chatbot ui not fine so assign me this issue i will fix it..

### ISSUE THREAD

**Issue by Nexusrex18** [ankit071105/Ticket-Booking#519]
### Description

so plz assign it under Hacktoberfest'24 

### Screenshots

![image](https://github.com/user-attachments/assets/faefc68b-a904-4009-a01e-90418db098c5)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/ankit071105/Ticket-Booking/blob/main/README.md)
- [ ] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [ ] I am willing to work on this issue (optional)

**Comment by himasnhu018** [comment]
assign me please @ankit071105
