### ISSUE TITLE
[BUG] add gssoc fest logo & update the readme

### ISSUE THREAD

**Issue by REHAN-18** [ankit071105/Ticket-Booking#522]
### Description

gssoc fest logo will enhance the repo & update the readme

### Screenshots

<img width="850" alt="Screenshot 2024-10-22 at 12 12 37 AM" src="https://github.com/user-attachments/assets/db0d75a7-1b7c-4075-a99c-6e05da4d7aed">
also adding this to repo will enhance the repo & HELP THE CONTRIBUTOR TO CONTRIBUTE!!!

### What browser are you seeing the problem on?

Safari

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/ankit071105/Ticket-Booking/blob/main/README.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by BlossomBreeze25** [comment]
can i work on this issue with you ?

**Comment by REHAN-18** [comment]
@ankit071105 bro done this see the pr #575
