### ISSUE TITLE
[BUG] While chatbot icon chatbot is not opening 

### ISSUE THREAD

**Issue by Sawan-Kushwah** [ankit071105/Ticket-Booking#531]
### Description

go on home page and click on chatbot it will not open

### What browser are you seeing the problem on?

Firefox

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/ankit071105/Ticket-Booking/blob/main/README.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by Balamurugan-cyber** [comment]
please assign this issue
