### ISSUE TITLE
[BUG] Improve the background of the navbar for small screens.

### ISSUE THREAD

**Issue by sayanp607** [ankit071105/Ticket-Booking#534]
### Description

The navbar when opened through clicking the toggle button, seems messy with a improper background behind it. The contributors option do not align with the existing UI there. Please  assign this task to me. I will fix the background size and will make it better for user experience .

### Screenshots

![Screenshot 2024-10-22 110713](https://github.com/user-attachments/assets/6ac91c0a-1129-49a8-8251-f25c03f4ce60)

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/ankit071105/Ticket-Booking/blob/main/README.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by arpit74170** [comment]
please Give this task to me i will fix it
