### ISSUE TITLE
Footer is missing in some sections 

### ISSUE THREAD

**Issue by adityalaxkar123** [ankit071105/Ticket-Booking#555]
In the terms & condition , privacy policy and etc. section don't have the footer section 

Me a GSSOC'24 extended member can you assign it to me

**Comment by sahare-mayur-0071** [comment]
@ankit071105 
I won't to work on this issue. Assign me this issue

**Comment by kartik-212004** [comment]
i want to work on this issue

**Comment by adityalaxkar123** [comment]
@ankit071105 assign this issue

**Comment by kartik-212004** [comment]
😭😭...i want to solve some issuess.
