### ISSUE TITLE
contact us page needs improvment

### ISSUE THREAD

**Issue by agarwalbhargavi** [ankit071105/Ticket-Booking#569]
### Description

the ui is not proper

### Any additional information?

<img width="956" alt="Screenshot 2024-10-24 004435" src="https://github.com/user-attachments/assets/7621df21-ebe0-41e4-8cff-e1a5adda273d">
this needs to be fixed
@ank

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/ankit071105/Ticket-Booking/blob/main/README.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by agarwalbhargavi** [comment]
@ankit071105 kindly assign me this issue

**Comment by himasnhu018** [comment]
assign me please that work @ankit071105

**Comment by byteom** [comment]
@ankit071105 assign to me
