### ISSUE TITLE
Add Concert Ticket Section 

### ISSUE THREAD

**Issue by kritts12** [ankit071105/Ticket-Booking#57]
## Issue Description 
We need to implement a dedicated section for booking concert tickets. This section should allow users to browse upcoming concerts, view details such as date, time, venue, and ticket prices, and complete the booking process.

I would like to work on this issue. Please assign this issue to me under gssoc-ext, GSSoC, hacktoberfest-accepted.

**Comment by ankit071105** [comment]
> ## Issue Description
> We need to implement a dedicated section for booking concert tickets. This section should allow users to browse upcoming concerts, view details such as date, time, venue, and ticket prices, and complete the booking process.
> 
> I would like to work on this issue. Please assign this issue to me under gssoc-ext, GSSoC, hacktoberfest-accepted.

sorry bro it is not a singing ticket  or. a dance ticket page . It is a ticket swaping of buses and train .
