### ISSUE TITLE
Improve Dark Mode 

### ISSUE THREAD

**Issue by kritts12** [ankit071105/Ticket-Booking#58]
## Issue Description 
The current dark mode of the website requires improvements in both design and functionality to enhance the user experience. The goal is to ensure that the dark mode provides better visual contrast, readability, and consistency across all pages.

I would like to work on this issue. Please assign this issue to me under gssoc-ext, GSSoC, hacktoberfest-accepted.

**Comment by INam1995** [comment]
My goal is to ensure better visual contrast, improved readability, and consistency across all pages in dark mode.

I would like to work on this issue. Please assign it to me under the labels gssoc-ext

**Comment by kritts12** [comment]
But I’ve been actively working on this issue and already made considerable progress. I’ll be submitting my PR shortly.
