### ISSUE TITLE
Add User-Friendly Navbar with 'Home,' 'About Us,' and 'Reviews' Sections 

### ISSUE THREAD

**Issue by Aayushibnsl** [ankit071105/Ticket-Booking#614]
### Description

To improve navigation and enhance user experience, a new navbar should be added to the site. The navbar will include key sections such as 'Home,' 'About Us,' and 'Reviews,' allowing users to quickly find important information with ease. And in this we can also create frequenty quesrion to ask , so user dont have to scroll down and search for it

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/ankit071105/Ticket-Booking/blob/main/README.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by Aayushibnsl** [comment]
Please assign me this . i would like to do and contribute

**Comment by pameladeysarkar2003** [comment]
please @ankit071105 assig the task to me i can contribute to it

**Comment by HarshKumar1121** [comment]
please   @ankit071105    assign this task to me so that i can contribute my best  for it .
