### ISSUE TITLE
[BUG] MISALIGNMENT OF THE ELEMENTS IN THE MAIN PAGE 

### ISSUE THREAD

**Issue by Nitinreddy09** [ankit071105/Ticket-Booking#627]
### Description

there is a misalignment of the elements in the main page, kindly assign me the task I would like to work on it.
![Screenshot 2024-10-25 195531](https://github.com/user-attachments/assets/df9ea8c6-da72-452f-8e09-1f5dd77bb1be)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/ankit071105/Ticket-Booking/blob/main/README.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by ankit071105** [comment]
Issued resolved it was an external css file issue it has been resolved
