### ISSUE TITLE
[BUG] No footer ❗

### ISSUE THREAD

**Issue by Nitinreddy09** [ankit071105/Ticket-Booking#628]
### Description

I would like to add a footer to the website.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/ankit071105/Ticket-Booking/blob/main/README.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by ankit071105** [comment]
Already added
