### ISSUE TITLE
[BUG] Logo issue

### ISSUE THREAD

**Issue by Nitinreddy09** [ankit071105/Ticket-Booking#629]
### Description

There is no logo or the existing logo doesn't show up, kindly assign me the task task , I would like to work on it.
![Screenshot 2024-10-25 195811](https://github.com/user-attachments/assets/1069c47a-f440-436f-aac7-d70c9db209bf)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/ankit071105/Ticket-Booking/blob/main/README.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by ankit071105** [comment]
Resolved bro due to css files link was not added so it was an error
