### ISSUE TITLE
[BUG] Poor alignment and CSS styling of the FAQ section

### ISSUE THREAD

**Issue by Nitinreddy09** [ankit071105/Ticket-Booking#631]
### Description

Poor alignment and CSS styling of the FAQ section, kindly assign me the task, I would like to work on it.

### Screenshots

![Screenshot 2024-10-25 195957](https://github.com/user-attachments/assets/c5f6febc-f27f-44db-b7bd-bac0b4a029f0)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/ankit071105/Ticket-Booking/blob/main/README.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by ankit071105** [comment]
Resolved this issued
