### ISSUE TITLE
Add Margin and Padding to "Why Book Us" Page for Improved Layout

### ISSUE THREAD

**Issue by Aayushibnsl** [ankit071105/Ticket-Booking#635]
### Description

The "Why Book Us" page currently lacks adequate margin and padding, resulting in a cramped layout that reduces readability and visual appeal. Adding margin and padding around elements on this page will create a cleaner, more attractive, and user-friendly interface.

### Any additional information?

The content on the "Why Book Us" page should have sufficient margin and padding, allowing elements to be better separated and improving readability.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/ankit071105/Ticket-Booking/blob/main/README.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by HarshKumar1121** [comment]
please ankit071105 assign this task to me .
