### ISSUE TITLE
Multiple footer logo sections in sell ticket 

### ISSUE THREAD

**Issue by srikanth-maganti** [ankit071105/Ticket-Booking#637]
### Description

footer in sell ticket page contains multiple footer logo section and sell your  tickets div is present in footer section

### Screenshots

![Screenshot (170)](https://github.com/user-attachments/assets/dc4cda87-58b3-4885-8c48-8c8f27e413f6)

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/ankit071105/Ticket-Booking/blob/main/README.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by srikanth-maganti** [comment]
assign it to me

**Comment by ankit071105** [comment]
It has been Resolved

**Comment by ankit071105** [comment]
Resolved the issue
