### ISSUE TITLE
[BUG] Two navigation on buy.html

### ISSUE THREAD

**Issue by byteom** [ankit071105/Ticket-Booking#640]
### Description

Issue:  There is two nav option on [Buy](https://ticket-booking-blue.vercel.app/buy.html).

Expected Behavior: There should one navigation option only

Steps to Reproduce:
Open the browser and navigate to the [Buy page](https://ticket-booking-blue.vercel.app/buy.html) of the ticket booking website.
Observe the navigation bar at the top of the page.
Look for the navigation options.
You will notice there are two navigation options present instead of one.
 

 

Screenshots
 
![image](https://github.com/user-attachments/assets/b2d3ba01-cf01-490a-903e-1f47919701bc)

/Assign this to me.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/ankit071105/Ticket-Booking/blob/main/README.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by ankit071105** [comment]
Resolved bro
