### ISSUE TITLE
Gmail and whatsapp logo size

### ISSUE THREAD

**Issue by shalini-bhandari** [ankit071105/Ticket-Booking#65]
<img width="1280" alt="Screenshot 2024-10-03 at 10 19 29" src="https://github.com/user-attachments/assets/61b8928b-f089-4435-b9f5-30f08250a56c">

logos are very large and visually overwhelming.
Kindly assign me this issue under gssoc-extd and hacktoberfest-accepted with appropriate level.

**Comment by DevamKumar25** [comment]
Hii,
I want to contribute and work on this project and resolve your, so please assign me this issue so that I can fulfil your requirements.
Thank You!

**Comment by vk-cse** [comment]
I want to work on this issue. kindly assign it to me..

**Comment by ankit071105** [comment]
> I want to work on this issue as logos are still very large. I will fix this issue asap. kindly assign it to me..

Already Resolve now @shalini-bhandari  @vk-cse  @Ibrangrd  @DevamKumar25
