### ISSUE TITLE
Register with Google or Phone Number on Ticket Booking

### ISSUE THREAD

**Issue by itbindu** [ankit071105/Ticket-Booking#67]
Registration through Google and phone number authentication. With Google sign-in, users can quickly access their accounts using their Google credentials. For those preferring mobile verification, phone number authentication provides a secure alternative, ensuring flexibility and convenience for all users. can you give me this issues pls, and i will do back ground also

**Comment by saurabhvybs** [comment]
@itbindu there is already a regular jwt authentication api available if you want to add google authentication make sure you don't change the regular api and also integrate it with reagular authentication

**Comment by ankit071105** [comment]
> @itbindu there is already a regular jwt authentication api available if you want to add google authentication make sure you don't change the regular api and also integrate it with regular authentication. and Ticket booking will be done from the personal dashboard of the user after the login part
> 
> @ankit071105 brother tell me if you are ready with the idea then i will handle the backend accordingly.

You can go for this but dont raise any error @saurabhvybs
