### ISSUE TITLE
Attention Everyone Due to tailwind Css there is an issue 

### ISSUE THREAD

**Issue by ankit071105** [ankit071105/Ticket-Booking#68]
Attention Everyone Due to tailwind Css there is an issue  that been seen whole page css got demolished and it is looking very bad Look into this if anyone wants i can assign you as bug issue . 
Best Regards,
Project Admin :- @ankit071105 
Mentor: @skddl007

**Comment by itbindu** [comment]
can you assign me i can do

**Comment by sanjay-kv** [comment]
@ankit071105 in the future you need not tag me. 
i can only help with managing label. 

you are using wrong labels. 

correct labels are gssoc-ext, hactoberfest-accepted

**Comment by ankit071105** [comment]
> @ankit071105 in the future you need not tag me. i can only help with managing label.
> 
> you are using wrong labels.
> 
> correct labels are gssoc-ext, hactoberfest-accepted

okay sir

**Comment by ankit071105** [comment]
> can you assign me i can do

Provide me a solution video or ss then i will assign you

**Comment by saurabhvybs** [comment]
@ankit071105 tell me in which file the tailwind is creating error just tell me i will fix that and if you have any figma design then please send it to me psaurabh51@gmail.com and assign it to me .

**Comment by sanjanasp786** [comment]
i would like to work on this issue...please assign this to me

**Comment by skddl007** [comment]
@saurabhvybs  we don't have available of figma design. you can check according to available issue
