### ISSUE TITLE
Want to enhance the ticket booking interface.

### ISSUE THREAD

**Issue by HS202022** [ankit071105/Ticket-Booking#71]
![image](https://github.com/user-attachments/assets/3337c7cf-2cea-4c40-9b5c-0062842015cf)
**it is really basic interface want to enhance it **

**Comment by HS202022** [comment]
also see the button its not visible properly i can fix it

**Comment by keerthana196** [comment]
Wanted to enhance ticket Booking and wanted to add models and data for the ticket booking from backed and will add more UI to the frontend of the ticket booking app
