### ISSUE TITLE
ATTENTION EVERYONE !!!!!!

### ISSUE THREAD

**Issue by ankit071105** [ankit071105/Ticket-Booking#795]
### Description

As You know tomorrow is the last day for HacktoberFest , So i want to tell all the contributor to contribute as much as you can in Open Source . Today till night 12 all the PR and issue will be closed So Resolve all of them .
Happy !!! Coding 
Project Admin 
@ankit071105 
Mentor 
@skddl007 
Project Manager 
@MastanSayyad

**Comment by MastanSayyad** [comment]
@ankit071105 last date is 10th Nov for gssoc

**Comment by ankit071105** [comment]
Okay bro I was not aware for that @MastanSayyad  okay I will extend the date
