### ISSUE TITLE
Improve Slider Design and Functionality

### ISSUE THREAD

**Issue by Dnyaneshpise** [ankit071105/Ticket-Booking#8]
#### The time interval for automatically changing images is not reset when using the arrow buttons. This means that even if I manually switch to the next image, the automatic transition continues without restarting. Instead, the timer should reset after clicking an arrow button, allowing the new image to remain for the full duration before the next automatic change.

![Screenshot 2024-10-01 222452](https://github.com/user-attachments/assets/a22f5cd0-954c-481c-adec-cb7ed7d49c89)

Also it should contain : Automatic Slide Transition, Slide Indicators, Enhance Navigation Arrows.

**Comment by ankit071105** [comment]
> #### The time interval for automatically changing images is not reset when using the arrow buttons. This means that even if I manually switch to the next image, the automatic transition continues without restarting. Instead, the timer should reset after clicking an arrow button, allowing the new image to remain for the full duration before the next automatic change.
> ![Screenshot 2024-10-01 222452](https://private-user-images.githubusercontent.com/93508573/372571830-a22f5cd0-954c-481c-adec-cb7ed7d49c89.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4MDMwMTMsIm5iZiI6MTcyNzgwMjcxMywicGF0aCI6Ii85MzUwODU3My8zNzI1NzE4MzAtYTIyZjVjZDAtOTU0Yy00ODFjLWFkZWMtY2I3ZWQ3ZDQ5Yzg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAxVDE3MTE1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3MjNlNzcyMTY3MjhjNzFlNTg2ODk0Y2Y1ZDY1NDJlYmEyZDY1NmM3NzAxNDg5YmI4M2VlNjNhNWYxYTMyOTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.qF4w1dTo26pnTW3a5LfvYnIxKQXRY3a84Hvr3ZfR82I)
> 
> Also it should contain : Automatic Slide Transition, Slide Indicators, Enhance Navigation Arrows.

You have solution for this you want to contribute ?

**Comment by saurabhvybs** [comment]
You can Assign me this role i can contribute to this functionality making it more efficient the way you want.

**Comment by dushyantkanav** [comment]
I can fix this issue. You can assign it to me

**Comment by ankit071105** [comment]
> I can fix this issue. You can assign it to me

already assign bro you can create new issue of work in the backend part
