### ISSUE TITLE
[BUG] Adding a Visitor counter in the footer

### ISSUE THREAD

**Issue by Peart-Guy** [ankit071105/Ticket-Booking#856]
### Description

I want to add a visitor counter to your website. I have given two samples. 
One in the body and other on the footer.

### Screenshots

![Screenshot 2024-10-26 004029](https://github.com/user-attachments/assets/228e0231-35fd-4021-8fd9-40df4f3a9acb)
![Screenshot 2024-10-31 141146](https://github.com/user-attachments/assets/9e7b123f-8ff0-4e68-9bb4-0783175f09e1)

### Any additional information?

You can choose whichever you like.
@ankit071105 Kindly assign me this issue

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/ankit071105/Ticket-Booking/blob/main/README.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by BhavikaPachauri** [comment]
if this issue is open can i work on it

**Comment by Peart-Guy** [comment]
@ankit071105  I opened the issue. Kindly assign me

**Comment by BhavikaPachauri** [comment]
okk
