### ISSUE TITLE
Working on Writing the Common Utility for Async Handler and ApiError

### ISSUE THREAD

**Issue by MOHINI1403** [ankit071105/Ticket-Booking#88]
We can work on writing the common utility for Async Function Handling and API Error Handling. 
Please assign this issue to me I will work on this and update the codes where we can use these utility.

**Comment by Ananya-vastare** [comment]
I would Like to work on this issue I am a gssoc contributor

**Comment by MOHINI1403** [comment]
I have raised the PR in response to the issue assigned and along with that also made the changes into the auth-controller please check the PR once if there is any issues that you are finding please comment on the PR I will resolve them.

**Comment by Ananya-vastare** [comment]
Okay will do that
