### ISSUE TITLE
TOGGLE SWITCH INSTEAD OF BUTTON

### ISSUE THREAD

**Issue by STDYGIT** [ankit071105/Ticket-Booking#90]
Button gives an old look to the website here is a switch which adds a cool animaiton in changing your website

![Screenshot 2024-10-02 at 12 44 31 PM](https://github.com/user-attachments/assets/a75c2235-1b33-4cfd-9137-d9c9460ea48f)
![Screenshot 2024-10-02 at 12 44 47 PM](https://github.com/user-attachments/assets/1c0de984-8664-48b4-b6d8-b5e244ec6a13)

**Comment by STDYGIT** [comment]
I would like to update your wbsite using these cool switch instead of button

**Comment by SHARKSEA16** [comment]
Hey @ankit071105 
Please assign this to me

**Comment by ankit071105** [comment]
Not reuqired
