### ISSUE TITLE
Enhance UI of the home page

### ISSUE THREAD

**Issue by sinhaudita** [ankit071105/Ticket-Booking#93]
The "Why book with us" section's UI can be enhance to make the overall webpage attractive. I want to implement a carousel or flip card feature for that section. Also I would like to align the icons and titles of this particular section to make it look uniform. Please assign this task to me.

**Comment by ankit071105** [comment]
Some same demo video or ss. @sinhaudita

**Comment by sinhaudita** [comment]
okay, i'll send it today.

**Comment by ankit071105** [comment]
> ticketify.1.mp4 
> This is a sample of what I have thought to implement.

working fine but make size small it is looking very big. in size @sinhaudita  send me the pr then

**Comment by ankit071105** [comment]
> Size has to be made small in height or width?
width size small and height 20px
