### ISSUE TITLE
Feature Request: Redesign Footer 

### ISSUE THREAD

**Issue by achintyasrivastav** [ankit071105/Ticket-Booking#95]
I propose a redesign of the footer section to improve usability and enhance visual appeal. The goal is to create a footer that provides users with easy access to important links and information while aligning with modern design trends.

Please label this request under Hacktoberfest 2024 and Girlscript Summer of Code 2024.

**Comment by abhinav120304** [comment]
Please label this request under Hacktoberfest 2024 and Girlscript Summer of Code 2024.

**Comment by ankit071105** [comment]
> Please label this request under Hacktoberfest 2024 and Girlscript Summer of Code 2024.
> 
> 

Bro already assigned created a new issue and follow the guidelines of Gssoc extend  and hacktober fest @abhinav120304
