### ISSUE TITLE
Update Button Style for Better User Interaction

### ISSUE THREAD

**Issue by Himanshusingh9647** [ankit071105/Ticket-Booking#99]
I would like to suggest an improvement to the current button style to make it more interactive and modern. Here are the proposed changes:

Add a smoother transition effect for hover interactions.

Adjust padding and margins to improve the button's responsiveness.

**Comment by Himanshusingh9647** [comment]
Please assign this issue to me I will work on this and will update the code accordingly.

**Comment by ankit071105** [comment]
> Please assign this issue to me I will work on this and will update the code accordingly.

okay first show us a demo video what do you want to perform in the task

**Comment by Himanshusingh9647** [comment]
https://github.com/user-attachments/assets/a57dce29-1ac8-442e-a27b-f9b4a111a928

**Comment by Himanshusingh9647** [comment]
I have attached the video above.

**Comment by ankit071105** [comment]
> I have attached the video above.

add some more professional and add some unique animations

**Comment by Himanshusingh9647** [comment]
https://github.com/user-attachments/assets/f909cdea-a336-45b9-988c-efbbcbe27dd9

**Comment by Himanshusingh9647** [comment]
https://github.com/user-attachments/assets/5983bf7d-d724-4f1a-a316-61ff93aeb560

**Comment by Himanshusingh9647** [comment]
added more transition and style matching the overall website theme

**Comment by ankit071105** [comment]
> Screen.Recording.2024-10-04.224823.mp4

this is quite impressive okay generate a PR of this i am assiging this to you . @Himanshusingh9647
